[package]
name = "exam-panel-app"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[lib]
name = "exam_panel_app"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.0", features = [] }

[dependencies]
tauri = { version = "2.0", features = [] }
serde = { workspace = true }
serde_json = { workspace = true }
exam-panel-core = { workspace = true }
exam-panel-storage = { workspace = true }
