//! Stage 1 Hard-Constraint Solver.
//!
//! Uses randomized MRV-directed backtracking with forward checking to construct
//! candidate assignment plans that strictly satisfy 100% of hard constraints (H1–H7).

use crate::domain::{
    Assignment, CampusId, ExamId, GradeId, LockKind, PanelKey, Problem, Role, RuleKey, SubjectId,
    TeacherId,
};
use crate::feasibility::{check_feasibility, FeasibilityReport};
use rand_chacha::ChaCha8Rng;
use rand_core::{RngCore, SeedableRng};
use serde::{Deserialize, Serialize};
use std::collections::{HashMap, HashSet};
use std::time::Instant;

/// Solver configuration options.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub struct SolveOptions {
    /// Random seed for deterministic reproducibility.
    pub seed: u64,
    /// Maximum wall-clock time in milliseconds before halting with LimitReached.
    pub time_limit_ms: u64,
    /// Maximum search nodes explored before halting with LimitReached.
    pub max_nodes: u64,
}

impl Default for SolveOptions {
    fn default() -> Self {
        Self {
            seed: 42,
            time_limit_ms: 2000,
            max_nodes: 2_000_000,
        }
    }
}

/// Statistics captured during hard solver execution.
#[derive(Debug, Clone, PartialEq, Eq, Default, Serialize, Deserialize)]
pub struct SolveStats {
    pub nodes: u64,
    pub backtracks: u64,
    pub elapsed_ms: u64,
}

/// A complete, valid candidate solution generated by the solver.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Solution {
    pub assignments: Vec<Assignment>,
    pub seed: u64,
    pub stats: SolveStats,
}

/// Errors returned when the hard solver cannot find a solution.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub enum SolveError {
    /// Pre-solve feasibility checks detected mathematical impossibility.
    Infeasible { report: FeasibilityReport },
    /// The search tree was exhaustively explored and proven to have no valid solution.
    Exhausted {
        stats: SolveStats,
        unfilled_panels: Vec<PanelKey>,
    },
    /// The solver reached the configured time limit or maximum node limit.
    LimitReached {
        stats: SolveStats,
        best_partial: Vec<Assignment>,
    },
}

impl std::fmt::Display for SolveError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Infeasible { report } => {
                write!(
                    f,
                    "problem is mathematically infeasible ({} errors)",
                    report.errors.len()
                )
            }
            Self::Exhausted {
                stats,
                unfilled_panels,
            } => {
                write!(
                    f,
                    "search space exhausted after {} nodes ({} panels unfilled)",
                    stats.nodes,
                    unfilled_panels.len()
                )
            }
            Self::LimitReached {
                stats,
                best_partial,
            } => {
                write!(
                    f,
                    "solver limit reached after {} nodes (best partial: {} assignments)",
                    stats.nodes,
                    best_partial.len()
                )
            }
        }
    }
}

impl std::error::Error for SolveError {}

/// A statically valid candidate triple (setter1, setter2, reviewer) for a panel.
/// If a subject only has 1 setter, s2 is `usize::MAX`.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
struct CandidateTriple {
    s1: usize,
    s2: usize,
    r: usize,
}

/// Solves for a complete, 100% hard-constraint-satisfying assignment plan.
///
/// Returns `Ok(Solution)` on success, or `Err(SolveError)` if infeasible, exhausted, or timed out.
pub fn solve_hard(problem: &Problem, opts: &SolveOptions) -> Result<Solution, SolveError> {
    // 1. Run pre-solve feasibility check; stop early on errors.
    let report = check_feasibility(problem);
    if !report.is_feasible() {
        return Err(SolveError::Infeasible { report });
    }

    let start_time = Instant::now();

    let num_teachers = problem.teachers.len();
    let subjects = problem.effective_subjects();
    let _num_subjects = subjects.len();

    let teacher_id_to_idx: HashMap<TeacherId, usize> = problem
        .teachers
        .iter()
        .enumerate()
        .map(|(i, t)| (t.id, i))
        .collect();

    let exam_id_to_idx: HashMap<ExamId, usize> = problem
        .exams
        .iter()
        .enumerate()
        .map(|(i, e)| (e.id, i))
        .collect();

    let grade_id_to_idx: HashMap<GradeId, usize> = problem
        .grades
        .iter()
        .enumerate()
        .map(|(i, g)| (g.id, i))
        .collect();

    let subject_id_to_idx: HashMap<SubjectId, usize> = subjects
        .iter()
        .enumerate()
        .map(|(i, s)| (s.id, i))
        .collect();

    let teacher_campuses: Vec<CampusId> = problem.teachers.iter().map(|t| t.campus_id).collect();

    let h4_setting = problem.rule_settings.iter().find(|s| s.key == RuleKey::H4);
    let h4_enabled = h4_setting.is_none_or(|s| s.enabled);
    let default_max_tasks_per_exam = h4_setting
        .and_then(|s| {
            s.params
                .get("max_tasks_per_exam")
                .and_then(serde_json::Value::as_u64)
        })
        .map_or(2, |v| v as usize);
    let default_max_setter_per_exam = h4_setting
        .and_then(|s| {
            s.params
                .get("max_setter_per_exam")
                .and_then(serde_json::Value::as_u64)
        })
        .map_or(1, |v| v as usize);

    // Forced placements
    let forced_placements =
        crate::domain::forced::find_forced_placements(problem).unwrap_or_default();
    let mut forced_counts = vec![0usize; num_teachers];
    let mut forced_tasks_per_exam = vec![vec![0usize; problem.exams.len()]; num_teachers];
    let mut forced_setters_per_exam = vec![vec![0usize; problem.exams.len()]; num_teachers];

    for p in &forced_placements {
        if let Some(&t_idx) = teacher_id_to_idx.get(&p.teacher_id) {
            forced_counts[t_idx] += 1;
            if let Some(&e_idx) = exam_id_to_idx.get(&p.panel.exam_id) {
                forced_tasks_per_exam[t_idx][e_idx] += 1;
                if p.role == Role::Setter {
                    forced_setters_per_exam[t_idx][e_idx] += 1;
                }
            }
        }
    }

    // Effective max tasks and setter tasks per teacher per exam
    let mut eff_max_tasks =
        vec![vec![default_max_tasks_per_exam; problem.exams.len()]; num_teachers];
    let mut eff_max_setter =
        vec![vec![default_max_setter_per_exam; problem.exams.len()]; num_teachers];
    for t_idx in 0..num_teachers {
        let t = &problem.teachers[t_idx];
        let configured = t
            .max_tasks_per_exam_override
            .map_or(default_max_tasks_per_exam, |v| v as usize);
        for e_idx in 0..problem.exams.len() {
            eff_max_tasks[t_idx][e_idx] = configured.max(forced_tasks_per_exam[t_idx][e_idx]);
            eff_max_setter[t_idx][e_idx] =
                default_max_setter_per_exam.max(forced_setters_per_exam[t_idx][e_idx]);
        }
    }

    // Extract quotas
    let mut lo = vec![0usize; num_teachers];
    let mut hi = vec![0usize; num_teachers];
    let mut quota = vec![0.0f64; num_teachers];

    for tq in &report.quotas {
        if let Some(&idx) = teacher_id_to_idx.get(&tq.teacher_id) {
            lo[idx] = tq.lo;
            hi[idx] = tq.hi;
            quota[idx] = tq.quota;
        }
    }

    // Panels list and mapping
    let all_panels = problem.all_panels();
    let total_panels = all_panels.len();

    if total_panels == 0 {
        return Ok(Solution {
            assignments: Vec::new(),
            seed: opts.seed,
            stats: SolveStats::default(),
        });
    }

    let mut panel_keys = Vec::with_capacity(total_panels);
    let mut panel_exam_idx = Vec::with_capacity(total_panels);
    let mut panel_grade_idx = Vec::with_capacity(total_panels);
    let mut panel_subject_idx = Vec::with_capacity(total_panels);

    for p in &all_panels {
        panel_keys.push(*p);
        panel_exam_idx.push(exam_id_to_idx[&p.exam_id]);
        panel_grade_idx.push(grade_id_to_idx[&p.grade_id]);
        panel_subject_idx.push(subject_id_to_idx[&p.subject_id]);
    }

    // Precompute candidate triples for each panel
    let mut static_triples: Vec<Vec<CandidateTriple>> = vec![Vec::new(); total_panels];
    let mut teacher_can_join_panel: Vec<Vec<bool>> = vec![vec![false; total_panels]; num_teachers];

    for p in 0..total_panels {
        let pkey = panel_keys[p];
        let s_idx = panel_subject_idx[p];
        let sub = &subjects[s_idx];
        let min_campuses = sub.min_campuses as usize;

        // Check forced placements for this panel
        let forced_p_setters: Vec<usize> = forced_placements
            .iter()
            .filter(|fp| fp.panel == pkey && fp.role == Role::Setter)
            .filter_map(|fp| teacher_id_to_idx.get(&fp.teacher_id).copied())
            .collect();
        let forced_p_reviewers: Vec<usize> = forced_placements
            .iter()
            .filter(|fp| fp.panel == pkey && fp.role == Role::Reviewer)
            .filter_map(|fp| teacher_id_to_idx.get(&fp.teacher_id).copied())
            .collect();

        // Check PIN locks for this panel
        let mut pinned_setters = Vec::new();
        let mut pinned_reviewers = Vec::new();
        let mut pinned_any = Vec::new();

        for lock in &problem.locks {
            if lock.kind == LockKind::Pin
                && lock.exam_id == pkey.exam_id
                && lock.grade_id == pkey.grade_id
                && lock.subject_id == pkey.subject_id
            {
                if let Some(&t_idx) = teacher_id_to_idx.get(&lock.teacher_id) {
                    match lock.role {
                        Some(Role::Setter) => pinned_setters.push(t_idx),
                        Some(Role::Reviewer) => pinned_reviewers.push(t_idx),
                        None => pinned_any.push(t_idx),
                    }
                }
            }
        }

        let mut eligible_setters = Vec::new();
        let mut eligible_reviewers = Vec::new();

        for (t, can_join) in teacher_can_join_panel
            .iter_mut()
            .enumerate()
            .take(num_teachers)
        {
            let s = crate::domain::forced::is_teacher_eligible(
                problem,
                problem.teachers[t].id,
                pkey.exam_id,
                pkey.grade_id,
                pkey.subject_id,
                Role::Setter,
            );
            let r = crate::domain::forced::is_teacher_eligible(
                problem,
                problem.teachers[t].id,
                pkey.exam_id,
                pkey.grade_id,
                pkey.subject_id,
                Role::Reviewer,
            );

            if s {
                eligible_setters.push(t);
            }
            if r {
                eligible_reviewers.push(t);
            }
            if s || r {
                can_join[p] = true;
            }
        }

        // Generate combinations from eligible teachers
        let setter_candidates = eligible_setters;
        let reviewer_candidates = eligible_reviewers;

        if sub.setters == 1 {
            // 1 setter, 1 reviewer
            for &s1 in &setter_candidates {
                for &r in &reviewer_candidates {
                    if s1 == r {
                        continue;
                    }
                    let c1 = teacher_campuses[s1];
                    let cr = teacher_campuses[r];
                    if min_campuses >= 2 && c1 == cr {
                        continue;
                    }

                    if !forced_p_setters.is_empty() && !forced_p_setters.contains(&s1) {
                        continue;
                    }
                    if !forced_p_reviewers.is_empty() && !forced_p_reviewers.contains(&r) {
                        continue;
                    }
                    if !pinned_setters.is_empty() && !pinned_setters.contains(&s1) {
                        continue;
                    }
                    if !pinned_reviewers.is_empty() && !pinned_reviewers.contains(&r) {
                        continue;
                    }
                    if !pinned_any.is_empty() && !pinned_any.iter().all(|&pa| pa == s1 || pa == r) {
                        continue;
                    }

                    static_triples[p].push(CandidateTriple {
                        s1,
                        s2: usize::MAX,
                        r,
                    });
                }
            }
        } else {
            // 2 setters, 1 reviewer
            for (i, &s1) in setter_candidates.iter().enumerate() {
                for &s2 in &setter_candidates[i + 1..] {
                    for &r in &reviewer_candidates {
                        if r == s1 || r == s2 {
                            continue;
                        }
                        let c1 = teacher_campuses[s1];
                        let c2 = teacher_campuses[s2];
                        let cr = teacher_campuses[r];
                        let mut distinct_campuses = HashSet::new();
                        distinct_campuses.insert(c1);
                        distinct_campuses.insert(c2);
                        distinct_campuses.insert(cr);
                        if distinct_campuses.len() < min_campuses {
                            continue;
                        }

                        if !forced_p_setters.is_empty() {
                            let has_all_fs =
                                forced_p_setters.iter().all(|&fs| fs == s1 || fs == s2);
                            if !has_all_fs {
                                continue;
                            }
                        }
                        if !forced_p_reviewers.is_empty() && !forced_p_reviewers.contains(&r) {
                            continue;
                        }
                        if !pinned_setters.is_empty() {
                            let has_all_s = pinned_setters.iter().all(|&ps| ps == s1 || ps == s2);
                            if !has_all_s {
                                continue;
                            }
                        }
                        if !pinned_reviewers.is_empty() && !pinned_reviewers.contains(&r) {
                            continue;
                        }
                        if !pinned_any.is_empty() {
                            let has_all_any =
                                pinned_any.iter().all(|&pa| pa == s1 || pa == s2 || pa == r);
                            if !has_all_any {
                                continue;
                            }
                        }

                        static_triples[p].push(CandidateTriple { s1, s2, r });
                    }
                }
            }
        }
    }

    // Verify static feasibility
    for p in 0..total_panels {
        if static_triples[p].is_empty() {
            let stats = SolveStats {
                elapsed_ms: start_time.elapsed().as_millis() as u64,
                ..Default::default()
            };
            return Err(SolveError::Exhausted {
                stats,
                unfilled_panels: vec![panel_keys[p]],
            });
        }
    }

    let mut rng = ChaCha8Rng::seed_from_u64(opts.seed);
    let mut assigned: Vec<Option<CandidateTriple>> = vec![None; total_panels];
    let mut unfilled: Vec<usize> = (0..total_panels).collect();

    let mut used_count = vec![0usize; num_teachers];
    let mut exam_tasks = vec![vec![0usize; problem.exams.len()]; num_teachers];
    let mut exam_setters = vec![vec![0usize; problem.exams.len()]; num_teachers];

    let mut stats = SolveStats::default();
    let mut best_partial_count = 0usize;
    let mut best_partial_assignments = Vec::new();

    let search_res = backtrack(
        &mut assigned,
        &mut unfilled,
        &mut used_count,
        &mut exam_tasks,
        &mut exam_setters,
        &eff_max_tasks,
        &eff_max_setter,
        &static_triples,
        &teacher_can_join_panel,
        &panel_exam_idx,
        &panel_keys,
        &problem.teachers,
        &lo,
        &hi,
        &quota,
        h4_enabled,
        &mut rng,
        opts,
        start_time,
        &mut stats,
        &mut best_partial_count,
        &mut best_partial_assignments,
    );

    stats.elapsed_ms = start_time.elapsed().as_millis() as u64;

    match search_res {
        Ok(()) => {
            let mut assignments = Vec::with_capacity(total_panels * 3);
            for p in 0..total_panels {
                if let Some(triple) = assigned[p] {
                    let key = panel_keys[p];
                    assignments.push(Assignment::new(
                        key.exam_id,
                        key.grade_id,
                        key.subject_id,
                        problem.teachers[triple.s1].id,
                        Role::Setter,
                        0,
                    ));
                    if triple.s2 != usize::MAX {
                        assignments.push(Assignment::new(
                            key.exam_id,
                            key.grade_id,
                            key.subject_id,
                            problem.teachers[triple.s2].id,
                            Role::Setter,
                            1,
                        ));
                    }
                    assignments.push(Assignment::new(
                        key.exam_id,
                        key.grade_id,
                        key.subject_id,
                        problem.teachers[triple.r].id,
                        Role::Reviewer,
                        0,
                    ));
                }
            }
            Ok(Solution {
                assignments,
                seed: opts.seed,
                stats,
            })
        }
        Err(err) => match err {
            SearchError::Exhausted => {
                let unfilled_panels = unfilled.iter().map(|&p| panel_keys[p]).collect();
                Err(SolveError::Exhausted {
                    stats,
                    unfilled_panels,
                })
            }
            SearchError::LimitReached => Err(SolveError::LimitReached {
                stats,
                best_partial: best_partial_assignments,
            }),
        },
    }
}

enum SearchError {
    Exhausted,
    LimitReached,
}

#[allow(clippy::too_many_arguments)]
fn backtrack(
    assigned: &mut [Option<CandidateTriple>],
    unfilled: &mut Vec<usize>,
    used_count: &mut [usize],
    exam_tasks: &mut [Vec<usize>],
    exam_setters: &mut [Vec<usize>],
    eff_max_tasks: &[Vec<usize>],
    eff_max_setter: &[Vec<usize>],
    static_triples: &[Vec<CandidateTriple>],
    teacher_can_join: &[Vec<bool>],
    panel_exam: &[usize],
    panel_keys: &[PanelKey],
    teachers: &[crate::domain::Teacher],
    lo: &[usize],
    hi: &[usize],
    quota: &[f64],
    h4: bool,
    rng: &mut ChaCha8Rng,
    opts: &SolveOptions,
    start_time: Instant,
    stats: &mut SolveStats,
    best_partial_count: &mut usize,
    best_partial: &mut Vec<Assignment>,
) -> Result<(), SearchError> {
    stats.nodes += 1;

    if stats.nodes.is_multiple_of(256)
        && (start_time.elapsed().as_millis() >= opts.time_limit_ms as u128
            || stats.nodes >= opts.max_nodes)
    {
        return Err(SearchError::LimitReached);
    }

    let assigned_count = assigned.len() - unfilled.len();
    if assigned_count > *best_partial_count {
        *best_partial_count = assigned_count;
        best_partial.clear();
        for p in 0..assigned.len() {
            if let Some(triple) = assigned[p] {
                let key = panel_keys[p];
                best_partial.push(Assignment::new(
                    key.exam_id,
                    key.grade_id,
                    key.subject_id,
                    teachers[triple.s1].id,
                    Role::Setter,
                    0,
                ));
                if triple.s2 != usize::MAX {
                    best_partial.push(Assignment::new(
                        key.exam_id,
                        key.grade_id,
                        key.subject_id,
                        teachers[triple.s2].id,
                        Role::Setter,
                        1,
                    ));
                }
                best_partial.push(Assignment::new(
                    key.exam_id,
                    key.grade_id,
                    key.subject_id,
                    teachers[triple.r].id,
                    Role::Reviewer,
                    0,
                ));
            }
        }
    }

    if unfilled.is_empty() {
        for t in 0..used_count.len() {
            if used_count[t] < lo[t] {
                return Err(SearchError::Exhausted);
            }
        }
        return Ok(());
    }

    // MRV heuristic
    let mut best_panel_idx_in_unfilled = 0;
    let mut min_valid_triples = usize::MAX;
    let mut best_valid_triples: Vec<CandidateTriple> = Vec::new();

    for (ui, &p) in unfilled.iter().enumerate() {
        let e = panel_exam[p];
        let mut valid_triples = Vec::new();

        for &triple in &static_triples[p] {
            let t1 = triple.s1;
            let tr = triple.r;

            if used_count[t1] >= hi[t1] || used_count[tr] >= hi[tr] {
                continue;
            }

            if h4
                && (exam_tasks[t1][e] >= eff_max_tasks[t1][e]
                    || exam_setters[t1][e] >= eff_max_setter[t1][e]
                    || exam_tasks[tr][e] >= eff_max_tasks[tr][e])
            {
                continue;
            }

            if triple.s2 != usize::MAX {
                let t2 = triple.s2;
                if used_count[t2] >= hi[t2] {
                    continue;
                }
                if h4
                    && (exam_tasks[t2][e] >= eff_max_tasks[t2][e]
                        || exam_setters[t2][e] >= eff_max_setter[t2][e])
                {
                    continue;
                }
            }

            valid_triples.push(triple);
        }

        if valid_triples.is_empty() {
            stats.backtracks += 1;
            return Err(SearchError::Exhausted);
        }

        if valid_triples.len() < min_valid_triples {
            min_valid_triples = valid_triples.len();
            best_panel_idx_in_unfilled = ui;
            best_valid_triples = valid_triples;
            if min_valid_triples == 1 {
                break;
            }
        }
    }

    let chosen_p = unfilled.remove(best_panel_idx_in_unfilled);
    let chosen_e = panel_exam[chosen_p];

    // Value ordering
    let mut scored_triples: Vec<(i64, CandidateTriple)> = best_valid_triples
        .into_iter()
        .map(|triple| {
            let mut deficit = (quota[triple.s1] - used_count[triple.s1] as f64)
                + (quota[triple.r] - used_count[triple.r] as f64);
            if triple.s2 != usize::MAX {
                deficit += quota[triple.s2] - used_count[triple.s2] as f64;
            }
            let jitter = (rng.next_u32() % 1000) as f64 / 10000.0;
            let score = ((deficit + jitter) * 10000.0) as i64;
            (score, triple)
        })
        .collect();

    scored_triples.sort_by_key(|a| std::cmp::Reverse(a.0));

    for (_, triple) in scored_triples {
        assigned[chosen_p] = Some(triple);
        used_count[triple.s1] += 1;
        exam_tasks[triple.s1][chosen_e] += 1;
        exam_setters[triple.s1][chosen_e] += 1;

        if triple.s2 != usize::MAX {
            used_count[triple.s2] += 1;
            exam_tasks[triple.s2][chosen_e] += 1;
            exam_setters[triple.s2][chosen_e] += 1;
        }

        used_count[triple.r] += 1;
        exam_tasks[triple.r][chosen_e] += 1;

        // Forward checking
        let mut lo_feasible = true;
        for t in 0..used_count.len() {
            let needed = lo[t].saturating_sub(used_count[t]);
            if needed > 0 {
                let available_panels = unfilled
                    .iter()
                    .filter(|&&up| {
                        let ue = panel_exam[up];
                        teacher_can_join[t][up] && (!h4 || exam_tasks[t][ue] < eff_max_tasks[t][ue])
                    })
                    .count();
                if available_panels < needed {
                    lo_feasible = false;
                    break;
                }
            }
        }

        if lo_feasible {
            let mut all_panels_have_triple = true;
            for &up in unfilled.iter() {
                let ue = panel_exam[up];
                let has_valid = static_triples[up].iter().any(|t| {
                    if used_count[t.s1] >= hi[t.s1] || used_count[t.r] >= hi[t.r] {
                        return false;
                    }
                    if h4
                        && (exam_tasks[t.s1][ue] >= eff_max_tasks[t.s1][ue]
                            || exam_setters[t.s1][ue] >= eff_max_setter[t.s1][ue]
                            || exam_tasks[t.r][ue] >= eff_max_tasks[t.r][ue])
                    {
                        return false;
                    }
                    if t.s2 != usize::MAX {
                        if used_count[t.s2] >= hi[t.s2] {
                            return false;
                        }
                        if h4
                            && (exam_tasks[t.s2][ue] >= eff_max_tasks[t.s2][ue]
                                || exam_setters[t.s2][ue] >= eff_max_setter[t.s2][ue])
                        {
                            return false;
                        }
                    }
                    true
                });

                if !has_valid {
                    all_panels_have_triple = false;
                    break;
                }
            }

            if all_panels_have_triple {
                let sub_res = backtrack(
                    assigned,
                    unfilled,
                    used_count,
                    exam_tasks,
                    exam_setters,
                    eff_max_tasks,
                    eff_max_setter,
                    static_triples,
                    teacher_can_join,
                    panel_exam,
                    panel_keys,
                    teachers,
                    lo,
                    hi,
                    quota,
                    h4,
                    rng,
                    opts,
                    start_time,
                    stats,
                    best_partial_count,
                    best_partial,
                );

                if sub_res.is_ok() {
                    return Ok(());
                }
                if let Err(SearchError::LimitReached) = sub_res {
                    return Err(SearchError::LimitReached);
                }
            }
        }

        // Backtrack unplace
        stats.backtracks += 1;
        assigned[chosen_p] = None;
        used_count[triple.s1] -= 1;
        exam_tasks[triple.s1][chosen_e] -= 1;
        exam_setters[triple.s1][chosen_e] -= 1;

        if triple.s2 != usize::MAX {
            used_count[triple.s2] -= 1;
            exam_tasks[triple.s2][chosen_e] -= 1;
            exam_setters[triple.s2][chosen_e] -= 1;
        }

        used_count[triple.r] -= 1;
        exam_tasks[triple.r][chosen_e] -= 1;
    }

    unfilled.push(chosen_p);
    stats.backtracks += 1;
    Err(SearchError::Exhausted)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::domain::{
        Campus, CampusId, Competency, Exam, ExamId, Grade, GradeId, GradeScope, Lock, LockId,
        LockKind, Role, RuleSetting, SchoolYear, SchoolYearId, Subject, SubjectId, Teacher,
        TeacherGrade,
    };
    use crate::validate::{validate_assignments, ValidateOptions};
    use rand::Rng;
    use std::time::Instant;

    fn make_valid_test_problem() -> Problem {
        let sy = SchoolYear {
            id: SchoolYearId(1),
            name: "2026-2027".to_string(),
            is_current: true,
        };
        let campuses = vec![
            Campus {
                id: CampusId(1),
                code: "CS1".to_string(),
                name: "Campus 1".to_string(),
                color: "#111".to_string(),
            },
            Campus {
                id: CampusId(2),
                code: "CS2".to_string(),
                name: "Campus 2".to_string(),
                color: "#222".to_string(),
            },
            Campus {
                id: CampusId(3),
                code: "CS3".to_string(),
                name: "Campus 3".to_string(),
                color: "#333".to_string(),
            },
            Campus {
                id: CampusId(4),
                code: "CS4".to_string(),
                name: "Campus 4".to_string(),
                color: "#444".to_string(),
            },
        ];
        let grades = vec![
            Grade {
                id: GradeId(1),
                code: 10,
                name: "Khối 10".to_string(),
                sort_order: 1,
            },
            Grade {
                id: GradeId(2),
                code: 11,
                name: "Khối 11".to_string(),
                sort_order: 2,
            },
            Grade {
                id: GradeId(3),
                code: 12,
                name: "Khối 12".to_string(),
                sort_order: 3,
            },
        ];

        let sub1 = Subject {
            id: SubjectId(1),
            code: "CHUNG".to_string(),
            name: "Chung".to_string(),
            color: "slate".to_string(),
            sort_order: 1,
            setters: 2,
            reviewers: 1,
            min_campuses: 2,
        };

        let exams = vec![
            Exam {
                id: ExamId(1),
                school_year_id: sy.id,
                code: "GK1".to_string(),
                name: "Giữa kỳ 1".to_string(),
                sort_order: 1,
            },
            Exam {
                id: ExamId(2),
                school_year_id: sy.id,
                code: "CK1".to_string(),
                name: "Cuối kỳ 1".to_string(),
                sort_order: 2,
            },
            Exam {
                id: ExamId(3),
                school_year_id: sy.id,
                code: "GK2".to_string(),
                name: "Giữa kỳ 2".to_string(),
                sort_order: 3,
            },
            Exam {
                id: ExamId(4),
                school_year_id: sy.id,
                code: "CK2".to_string(),
                name: "Cuối kỳ 2".to_string(),
                sort_order: 4,
            },
        ];

        let teachers = vec![
            Teacher {
                id: TeacherId(1),
                full_name: "Nguyễn Văn An".to_string(),
                display_name: None,
                campus_id: CampusId(1),
                load_weight: 1.0,
                active: true,
                note: None,
                code: None,
                quota_override: None,
                max_tasks_per_exam_override: None,
            },
            Teacher {
                id: TeacherId(2),
                full_name: "Trần Thị Bình".to_string(),
                display_name: None,
                campus_id: CampusId(1),
                load_weight: 1.0,
                active: true,
                note: None,
                code: None,
                quota_override: None,
                max_tasks_per_exam_override: None,
            },
            Teacher {
                id: TeacherId(3),
                full_name: "Lê Hoàng Cường".to_string(),
                display_name: None,
                campus_id: CampusId(2),
                load_weight: 1.0,
                active: true,
                note: None,
                code: None,
                quota_override: None,
                max_tasks_per_exam_override: None,
            },
            Teacher {
                id: TeacherId(4),
                full_name: "Phạm Minh Đức".to_string(),
                display_name: None,
                campus_id: CampusId(2),
                load_weight: 1.0,
                active: true,
                note: None,
                code: None,
                quota_override: None,
                max_tasks_per_exam_override: None,
            },
            Teacher {
                id: TeacherId(5),
                full_name: "Hoàng Thu Giang".to_string(),
                display_name: None,
                campus_id: CampusId(3),
                load_weight: 1.0,
                active: true,
                note: None,
                code: None,
                quota_override: None,
                max_tasks_per_exam_override: None,
            },
            Teacher {
                id: TeacherId(6),
                full_name: "Vũ Hải Hà".to_string(),
                display_name: None,
                campus_id: CampusId(3),
                load_weight: 0.5,
                active: true,
                note: Some("Bán thời gian".to_string()),
                code: None,
                quota_override: None,
                max_tasks_per_exam_override: None,
            },
            Teacher {
                id: TeacherId(7),
                full_name: "Đặng Quốc Hùng".to_string(),
                display_name: None,
                campus_id: CampusId(3),
                load_weight: 1.0,
                active: true,
                note: None,
                code: None,
                quota_override: None,
                max_tasks_per_exam_override: None,
            },
            Teacher {
                id: TeacherId(8),
                full_name: "Bùi Thị Lan".to_string(),
                display_name: None,
                campus_id: CampusId(4),
                load_weight: 1.0,
                active: true,
                note: None,
                code: None,
                quota_override: None,
                max_tasks_per_exam_override: None,
            },
            Teacher {
                id: TeacherId(9),
                full_name: "Đỗ Tuấn Minh".to_string(),
                display_name: None,
                campus_id: CampusId(4),
                load_weight: 1.0,
                active: true,
                note: None,
                code: None,
                quota_override: None,
                max_tasks_per_exam_override: None,
            },
            Teacher {
                id: TeacherId(10),
                full_name: "Ngô Phương Nam".to_string(),
                display_name: None,
                campus_id: CampusId(1),
                load_weight: 1.0,
                active: true,
                note: None,
                code: None,
                quota_override: None,
                max_tasks_per_exam_override: None,
            },
            Teacher {
                id: TeacherId(11),
                full_name: "Dương Thùy Trang".to_string(),
                display_name: None,
                campus_id: CampusId(2),
                load_weight: 1.0,
                active: true,
                note: None,
                code: None,
                quota_override: None,
                max_tasks_per_exam_override: None,
            },
        ];

        let tg_tuples = [
            (1, 1),
            (3, 1),
            (5, 1),
            (8, 1),
            (2, 2),
            (4, 2),
            (6, 2),
            (9, 2),
            (1, 2),
            (3, 3),
            (7, 3),
            (10, 3),
            (11, 3),
            (2, 3),
        ];

        let mut teacher_grades = Vec::new();
        let mut competencies = Vec::new();

        for (tid, gid) in tg_tuples {
            teacher_grades.push(TeacherGrade {
                teacher_id: TeacherId(tid),
                school_year_id: sy.id,
                grade_id: GradeId(gid),
            });
        }

        for tid in 1..=11 {
            competencies.push(Competency {
                teacher_id: TeacherId(tid),
                subject_id: SubjectId(1),
                role: Role::Setter,
                grade_scope: GradeScope::Taught,
            });
            competencies.push(Competency {
                teacher_id: TeacherId(tid),
                subject_id: SubjectId(1),
                role: Role::Reviewer,
                grade_scope: GradeScope::Taught,
            });
        }

        Problem {
            school_year: sy,
            campuses,
            grades,
            subjects: vec![sub1],
            exams,
            teachers,
            teacher_grades,
            competencies,
            unavailabilities: vec![],
            locks: vec![],
            rule_settings: RuleSetting::default_settings(),
        }
    }

    #[test]
    fn test_solve_hard_produces_zero_violations() {
        let problem = make_valid_test_problem();
        let opts = SolveOptions {
            seed: 42,
            time_limit_ms: 5000,
            max_nodes: 500_000,
        };

        let result = solve_hard(&problem, &opts);
        assert!(result.is_ok(), "Expected solver success, got: {result:?}");

        let sol = result.unwrap();
        assert_eq!(sol.assignments.len(), 36);

        let violations = validate_assignments(
            &problem,
            &sol.assignments,
            &ValidateOptions {
                require_complete: true,
            },
        );
        assert!(
            violations.is_empty(),
            "Expected 0 violations, found {}: {violations:?}",
            violations.len()
        );
    }

    #[test]
    fn test_solve_demo_seed_returns_valid_solution() {
        let problem = make_valid_test_problem();
        let opts = SolveOptions {
            seed: 42,
            time_limit_ms: 2000,
            max_nodes: 500_000,
        };

        let result = solve_hard(&problem, &opts);
        assert!(result.is_ok(), "solve_hard failed: {:?}", result.err());

        let solution = result.unwrap();
        assert_eq!(solution.assignments.len(), 36);

        let violations = validate_assignments(
            &problem,
            &solution.assignments,
            &ValidateOptions {
                require_complete: true,
            },
        );
        assert!(
            violations.is_empty(),
            "returned solution has violations: {violations:?}"
        );
    }

    #[test]
    fn test_solver_determinism_and_multi_seed_variation() {
        let problem = make_valid_test_problem();

        let opts1 = SolveOptions {
            seed: 12345,
            ..Default::default()
        };
        let sol1a = solve_hard(&problem, &opts1).expect("sol1a");
        let sol1b = solve_hard(&problem, &opts1).expect("sol1b");
        assert_eq!(
            sol1a.assignments, sol1b.assignments,
            "same seed must produce identical assignments"
        );

        let opts2 = SolveOptions {
            seed: 98765,
            ..Default::default()
        };
        let sol2 = solve_hard(&problem, &opts2).expect("sol2");
        assert_ne!(
            sol1a.assignments, sol2.assignments,
            "different seeds should produce distinct assignments"
        );
    }

    #[test]
    fn test_solver_stops_early_on_infeasible_problem() {
        let mut problem = make_valid_test_problem();
        // Conflicting PIN + FORBID
        problem.locks.push(Lock {
            id: LockId(1),
            exam_id: ExamId(1),
            grade_id: GradeId(1),
            subject_id: SubjectId(1),
            teacher_id: TeacherId(1),
            role: Some(Role::Setter),
            kind: LockKind::Pin,
        });
        problem.locks.push(Lock {
            id: LockId(2),
            exam_id: ExamId(1),
            grade_id: GradeId(1),
            subject_id: SubjectId(1),
            teacher_id: TeacherId(1),
            role: None,
            kind: LockKind::Forbid,
        });

        let opts = SolveOptions::default();
        let res = solve_hard(&problem, &opts);
        assert!(matches!(res, Err(SolveError::Infeasible { .. })));
    }

    #[test]
    fn test_performance_timing_demo_seed() {
        let problem = make_valid_test_problem();
        let opts = SolveOptions {
            seed: 42,
            time_limit_ms: 2000,
            max_nodes: 500_000,
        };

        let start = Instant::now();
        let sol = solve_hard(&problem, &opts).expect("demo solve");
        let elapsed = start.elapsed();

        println!(
            "Demo seed solve time: {:?} (nodes: {}, backtracks: {})",
            elapsed, sol.stats.nodes, sol.stats.backtracks
        );
        assert_eq!(sol.assignments.len(), 36);
    }

    #[test]
    fn test_performance_synthetic_40_teacher_instance() {
        let sy = SchoolYear {
            id: SchoolYearId(1),
            name: "2026-2027".to_string(),
            is_current: true,
        };

        let campuses: Vec<Campus> = (1..=6)
            .map(|c| Campus {
                id: CampusId(c),
                code: format!("CS{c}"),
                name: format!("Campus {c}"),
                color: "#1e40af".to_string(),
            })
            .collect();

        let grades: Vec<Grade> = (1..=3)
            .map(|g| Grade {
                id: GradeId(g),
                code: (9 + g) as i32,
                name: format!("Khối {}", 9 + g),
                sort_order: g as i32,
            })
            .collect();

        let exams: Vec<Exam> = (1..=4)
            .map(|e| Exam {
                id: ExamId(e),
                school_year_id: sy.id,
                code: format!("EX{e}"),
                name: format!("Kỳ thi {e}"),
                sort_order: e as i32,
            })
            .collect();

        let mut teachers = Vec::with_capacity(40);
        let mut teacher_grades = Vec::new();

        for tid in 1..=40 {
            let cid = ((tid - 1) % 6) + 1;
            teachers.push(Teacher {
                id: TeacherId(tid),
                full_name: format!("Giáo viên {tid}"),
                display_name: None,
                campus_id: CampusId(cid),
                load_weight: 1.0,
                active: true,
                note: None,
                code: None,
                quota_override: None,
                max_tasks_per_exam_override: None,
            });

            let g1 = ((tid - 1) % 3) + 1;
            teacher_grades.push(TeacherGrade {
                teacher_id: TeacherId(tid),
                school_year_id: sy.id,
                grade_id: GradeId(g1),
            });
            if tid % 2 == 0 {
                let g2 = (g1 % 3) + 1;
                teacher_grades.push(TeacherGrade {
                    teacher_id: TeacherId(tid),
                    school_year_id: sy.id,
                    grade_id: GradeId(g2),
                });
            }
        }

        let sub1 = Subject {
            id: SubjectId(1),
            code: "CHUNG".to_string(),
            name: "Chung".to_string(),
            color: "slate".to_string(),
            sort_order: 1,
            setters: 2,
            reviewers: 1,
            min_campuses: 2,
        };

        let mut competencies = Vec::new();
        for t in &teachers {
            competencies.push(Competency {
                teacher_id: t.id,
                subject_id: sub1.id,
                role: Role::Setter,
                grade_scope: GradeScope::Taught,
            });
            competencies.push(Competency {
                teacher_id: t.id,
                subject_id: sub1.id,
                role: Role::Reviewer,
                grade_scope: GradeScope::Taught,
            });
        }

        let problem = Problem {
            school_year: sy,
            campuses,
            grades,
            subjects: vec![sub1],
            exams,
            teachers,
            teacher_grades,
            competencies,
            unavailabilities: vec![],
            locks: vec![],
            rule_settings: RuleSetting::default_settings(),
        };

        let opts = SolveOptions {
            seed: 777,
            time_limit_ms: 3000,
            max_nodes: 500_000,
        };

        let start = Instant::now();
        let result = solve_hard(&problem, &opts);
        let elapsed = start.elapsed();

        assert!(
            result.is_ok(),
            "synthetic 40 solve failed: {:?}",
            result.err()
        );
        let solution = result.unwrap();
        assert_eq!(solution.assignments.len(), 36);

        let violations = validate_assignments(
            &problem,
            &solution.assignments,
            &ValidateOptions {
                require_complete: true,
            },
        );
        assert!(violations.is_empty(), "violations: {violations:?}");

        println!(
            "Synthetic 40-teacher solve time: {:?} (nodes: {}, backtracks: {})",
            elapsed, solution.stats.nodes, solution.stats.backtracks
        );
    }

    fn brute_force_has_solution(problem: &Problem) -> bool {
        let panels = problem.all_panels();
        let teachers: Vec<TeacherId> = problem.teachers.iter().map(|t| t.id).collect();
        let n = teachers.len();

        let mut candidate_panels: Vec<Vec<Vec<Assignment>>> = Vec::new();
        for p in &panels {
            let sub = problem
                .effective_subjects()
                .into_iter()
                .find(|s| s.id == p.subject_id)
                .unwrap();
            let mut list = Vec::new();

            if sub.setters == 1 && sub.reviewers == 1 {
                for i in 0..n {
                    for j in 0..n {
                        if i == j {
                            continue;
                        }
                        let assigns = vec![
                            Assignment::new(
                                p.exam_id,
                                p.grade_id,
                                p.subject_id,
                                teachers[i],
                                Role::Setter,
                                0,
                            ),
                            Assignment::new(
                                p.exam_id,
                                p.grade_id,
                                p.subject_id,
                                teachers[j],
                                Role::Reviewer,
                                0,
                            ),
                        ];
                        let v = validate_assignments(
                            problem,
                            &assigns,
                            &ValidateOptions {
                                require_complete: false,
                            },
                        );
                        if v.is_empty() {
                            list.push(assigns);
                        }
                    }
                }
            } else if sub.setters == 2 && sub.reviewers == 1 {
                for i in 0..n {
                    for j in (i + 1)..n {
                        for k in 0..n {
                            if k == i || k == j {
                                continue;
                            }
                            let assigns = vec![
                                Assignment::new(
                                    p.exam_id,
                                    p.grade_id,
                                    p.subject_id,
                                    teachers[i],
                                    Role::Setter,
                                    0,
                                ),
                                Assignment::new(
                                    p.exam_id,
                                    p.grade_id,
                                    p.subject_id,
                                    teachers[j],
                                    Role::Setter,
                                    1,
                                ),
                                Assignment::new(
                                    p.exam_id,
                                    p.grade_id,
                                    p.subject_id,
                                    teachers[k],
                                    Role::Reviewer,
                                    0,
                                ),
                            ];
                            let v = validate_assignments(
                                problem,
                                &assigns,
                                &ValidateOptions {
                                    require_complete: false,
                                },
                            );
                            if v.is_empty() {
                                list.push(assigns);
                            }
                        }
                    }
                }
            }

            candidate_panels.push(list);
        }

        fn search(
            idx: usize,
            candidate_panels: &[Vec<Vec<Assignment>>],
            current: &mut Vec<Assignment>,
            problem: &Problem,
        ) -> bool {
            if idx == candidate_panels.len() {
                return validate_assignments(
                    problem,
                    current,
                    &ValidateOptions {
                        require_complete: true,
                    },
                )
                .is_empty();
            }

            for panel_assigns in &candidate_panels[idx] {
                let start_len = current.len();
                current.extend_from_slice(panel_assigns);
                let v = validate_assignments(
                    problem,
                    current,
                    &ValidateOptions {
                        require_complete: false,
                    },
                );
                if v.is_empty() && search(idx + 1, candidate_panels, current, problem) {
                    return true;
                }
                current.truncate(start_len);
            }
            false
        }

        let mut current = Vec::new();
        search(0, &candidate_panels, &mut current, problem)
    }

    #[test]
    fn test_cross_check_300_tiny_instances() {
        let mut rng = ChaCha8Rng::seed_from_u64(20261004);
        let num_instances = 300;
        let mut feasible_count = 0;
        let mut infeasible_count = 0;
        let mut backtrack_count = 0;

        for instance_idx in 0..num_instances {
            let sy = SchoolYear {
                id: SchoolYearId(1),
                name: "2026-2027".to_string(),
                is_current: true,
            };
            let c1 = Campus {
                id: CampusId(1),
                code: "C1".to_string(),
                name: "C1".to_string(),
                color: "#111".to_string(),
            };
            let c2 = Campus {
                id: CampusId(2),
                code: "C2".to_string(),
                name: "C2".to_string(),
                color: "#222".to_string(),
            };
            let g1 = Grade {
                id: GradeId(1),
                code: 10,
                name: "G10".to_string(),
                sort_order: 1,
            };
            let sub1 = Subject {
                id: SubjectId(1),
                code: "VL".to_string(),
                name: "Vật lí".to_string(),
                color: "blue".to_string(),
                sort_order: 1,
                setters: 2,
                reviewers: 1,
                min_campuses: 2,
            };
            let sub2 = Subject {
                id: SubjectId(2),
                code: "CN".to_string(),
                name: "Công nghệ".to_string(),
                color: "green".to_string(),
                sort_order: 2,
                setters: 2,
                reviewers: 1,
                min_campuses: 2,
            };
            let e1 = Exam {
                id: ExamId(1),
                school_year_id: sy.id,
                code: "GK1".to_string(),
                name: "GK1".to_string(),
                sort_order: 1,
            };

            let num_teachers = 6;
            let mut teachers = Vec::new();
            let mut teacher_grades = Vec::new();
            let mut competencies = Vec::new();

            for tid in 1..=num_teachers {
                let camp = if tid <= 3 {
                    CampusId(1)
                } else if tid == 4 {
                    if rng.gen_bool(0.6) {
                        CampusId(1)
                    } else {
                        CampusId(2)
                    }
                } else if tid == 5 {
                    CampusId(2)
                } else {
                    if rng.gen_bool(0.5) {
                        CampusId(2)
                    } else {
                        CampusId(1)
                    }
                };

                teachers.push(Teacher {
                    id: TeacherId(tid as i64),
                    full_name: format!("T{tid}"),
                    display_name: None,
                    campus_id: camp,
                    load_weight: 1.0,
                    active: true,
                    note: None,
                    code: None,
                    quota_override: None,
                    max_tasks_per_exam_override: None,
                });
                teacher_grades.push(TeacherGrade {
                    teacher_id: TeacherId(tid as i64),
                    school_year_id: sy.id,
                    grade_id: GradeId(1),
                });

                // Random competencies across sub1 and sub2
                let p_sub1 = if tid <= 3 { 0.85 } else { 0.55 };
                let p_sub2 = if tid >= 4 { 0.85 } else { 0.55 };

                if rng.gen_bool(p_sub1) {
                    competencies.push(Competency {
                        teacher_id: TeacherId(tid as i64),
                        subject_id: SubjectId(1),
                        role: Role::Setter,
                        grade_scope: GradeScope::Taught,
                    });
                }
                if rng.gen_bool(p_sub1) {
                    competencies.push(Competency {
                        teacher_id: TeacherId(tid as i64),
                        subject_id: SubjectId(1),
                        role: Role::Reviewer,
                        grade_scope: GradeScope::Taught,
                    });
                }
                if rng.gen_bool(p_sub2) {
                    competencies.push(Competency {
                        teacher_id: TeacherId(tid as i64),
                        subject_id: SubjectId(2),
                        role: Role::Setter,
                        grade_scope: GradeScope::Taught,
                    });
                }
                if rng.gen_bool(p_sub2) {
                    competencies.push(Competency {
                        teacher_id: TeacherId(tid as i64),
                        subject_id: SubjectId(2),
                        role: Role::Reviewer,
                        grade_scope: GradeScope::Taught,
                    });
                }
            }

            // Ensure each teacher has at least one competency so they aren't completely dead
            for tid in 1..=num_teachers {
                if !competencies
                    .iter()
                    .any(|c| c.teacher_id == TeacherId(tid as i64))
                {
                    competencies.push(Competency {
                        teacher_id: TeacherId(tid as i64),
                        subject_id: SubjectId(if tid <= 3 { 1 } else { 2 }),
                        role: Role::Setter,
                        grade_scope: GradeScope::Taught,
                    });
                }
            }

            let mut rule_settings = RuleSetting::default_settings();
            if let Some(h4) = rule_settings.iter_mut().find(|r| r.key == RuleKey::H4) {
                h4.params["max_tasks_per_exam"] = serde_json::json!(1);
            }

            let problem = Problem {
                school_year: sy,
                campuses: vec![c1, c2],
                grades: vec![g1],
                subjects: vec![sub1, sub2],
                exams: vec![e1],
                teachers,
                teacher_grades,
                competencies,
                unavailabilities: vec![],
                locks: vec![],
                rule_settings,
            };

            let bf_feasible = brute_force_has_solution(&problem);

            let opts = SolveOptions {
                seed: 42 + instance_idx as u64,
                time_limit_ms: 1000,
                max_nodes: 50_000,
            };

            let res = solve_hard(&problem, &opts);
            match res {
                Ok(sol) => {
                    assert!(
                        bf_feasible,
                        "Instance {instance_idx}: Solver found solution but brute force said infeasible!"
                    );
                    let v = validate_assignments(
                        &problem,
                        &sol.assignments,
                        &ValidateOptions {
                            require_complete: true,
                        },
                    );
                    assert!(
                        v.is_empty(),
                        "Instance {instance_idx} produced violations: {v:?}"
                    );
                    feasible_count += 1;
                    if sol.stats.backtracks > 0 {
                        backtrack_count += 1;
                    }
                }
                Err(_) => {
                    assert!(
                        !bf_feasible,
                        "Instance {instance_idx}: Brute force found solution but solver reported infeasible!"
                    );
                    infeasible_count += 1;
                }
            }
        }

        let backtrack_pct = if feasible_count > 0 {
            (backtrack_count as f64 / feasible_count as f64) * 100.0
        } else {
            0.0
        };

        println!(
            "Cross-check: {} instances tested | Feasible: {}, Infeasible: {} | Backtracked: {} ({:.1}% of feasible)",
            num_instances, feasible_count, infeasible_count, backtrack_count, backtrack_pct
        );

        assert_eq!(feasible_count + infeasible_count, num_instances);
        assert!(feasible_count > 0, "Expected some feasible instances");
        assert!(infeasible_count > 0, "Expected some infeasible instances");
        assert!(backtrack_count > 0, "Expected some backtracked instances");
    }
}
