//! Stage 1 Hard-Constraint Solver.
//!
//! Uses randomized MRV-directed backtracking with forward checking to construct
//! candidate assignment plans that strictly satisfy 100% of hard constraints (H1–H7).

use crate::domain::{
    Assignment, CampusId, ExamId, GradeId, LockKind, PanelKey, Problem, Role, RuleKey, TeacherId,
};
use crate::feasibility::{check_feasibility, FeasibilityReport};
use rand_chacha::ChaCha8Rng;
use rand_core::{RngCore, SeedableRng};
use serde::{Deserialize, Serialize};
use std::collections::{HashMap, HashSet};
use std::time::Instant;

/// Solver configuration options.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub struct SolveOptions {
    /// Random seed for deterministic reproducibility.
    pub seed: u64,
    /// Maximum wall-clock time in milliseconds before halting with LimitReached.
    pub time_limit_ms: u64,
    /// Maximum search nodes explored before halting with LimitReached.
    pub max_nodes: u64,
}

impl Default for SolveOptions {
    fn default() -> Self {
        Self {
            seed: 42,
            time_limit_ms: 2000,
            max_nodes: 2_000_000,
        }
    }
}

/// Statistics captured during hard solver execution.
#[derive(Debug, Clone, PartialEq, Eq, Default, Serialize, Deserialize)]
pub struct SolveStats {
    pub nodes: u64,
    pub backtracks: u64,
    pub elapsed_ms: u64,
}

/// A complete, valid candidate solution generated by the solver.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Solution {
    pub assignments: Vec<Assignment>,
    pub seed: u64,
    pub stats: SolveStats,
}

/// Errors returned when the hard solver cannot find a solution.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub enum SolveError {
    /// Pre-solve feasibility checks detected mathematical impossibility.
    Infeasible { report: FeasibilityReport },
    /// The search tree was exhaustively explored and proven to have no valid solution.
    Exhausted {
        stats: SolveStats,
        unfilled_panels: Vec<PanelKey>,
    },
    /// The solver reached the configured time limit or maximum node limit.
    LimitReached {
        stats: SolveStats,
        best_partial: Vec<Assignment>,
    },
}

impl std::fmt::Display for SolveError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Infeasible { report } => {
                write!(
                    f,
                    "problem is mathematically infeasible ({} errors)",
                    report.errors.len()
                )
            }
            Self::Exhausted {
                stats,
                unfilled_panels,
            } => {
                write!(
                    f,
                    "search space exhausted after {} nodes ({} panels unfilled)",
                    stats.nodes,
                    unfilled_panels.len()
                )
            }
            Self::LimitReached {
                stats,
                best_partial,
            } => {
                write!(
                    f,
                    "solver limit reached after {} nodes (best partial: {} assignments)",
                    stats.nodes,
                    best_partial.len()
                )
            }
        }
    }
}

impl std::error::Error for SolveError {}

/// Compact bitset supporting up to 256 teachers.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub struct TeacherBitSet([u64; 4]);

impl TeacherBitSet {
    #[must_use]
    pub const fn new() -> Self {
        Self([0; 4])
    }

    pub fn insert(&mut self, idx: usize) {
        if idx < 256 {
            self.0[idx / 64] |= 1u64 << (idx % 64);
        }
    }

    pub fn remove(&mut self, idx: usize) {
        if idx < 256 {
            self.0[idx / 64] &= !(1u64 << (idx % 64));
        }
    }

    #[must_use]
    pub const fn contains(&self, idx: usize) -> bool {
        if idx < 256 {
            (self.0[idx / 64] & (1u64 << (idx % 64))) != 0
        } else {
            false
        }
    }
}

/// A statically valid candidate triple (setter1, setter2, reviewer) for a panel.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
struct CandidateTriple {
    s1: usize,
    s2: usize,
    r: usize,
}

/// Solves for a complete, 100% hard-constraint-satisfying assignment plan.
///
/// Returns `Ok(Solution)` on success, or `Err(SolveError)` if infeasible, exhausted, or timed out.
pub fn solve_hard(problem: &Problem, opts: &SolveOptions) -> Result<Solution, SolveError> {
    // 1. Run pre-solve feasibility check; stop early on errors.
    let report = check_feasibility(problem);
    if !report.is_feasible() {
        return Err(SolveError::Infeasible { report });
    }

    let start_time = Instant::now();

    let num_teachers = problem.teachers.len();
    let num_exams = problem.exams.len();
    let num_grades = problem.grades.len();
    let total_panels = num_exams * num_grades;

    if total_panels == 0 {
        return Ok(Solution {
            assignments: Vec::new(),
            seed: opts.seed,
            stats: SolveStats::default(),
        });
    }

    // Mapping between IDs and dense indices
    let teacher_id_to_idx: HashMap<TeacherId, usize> = problem
        .teachers
        .iter()
        .enumerate()
        .map(|(i, t)| (t.id, i))
        .collect();

    let exam_id_to_idx: HashMap<ExamId, usize> = problem
        .exams
        .iter()
        .enumerate()
        .map(|(i, e)| (e.id, i))
        .collect();

    let grade_id_to_idx: HashMap<GradeId, usize> = problem
        .grades
        .iter()
        .enumerate()
        .map(|(i, g)| (g.id, i))
        .collect();

    let teacher_campuses: Vec<CampusId> = problem.teachers.iter().map(|t| t.campus_id).collect();

    let h4_enabled = problem
        .rule_settings
        .iter()
        .find(|s| s.key == RuleKey::H4)
        .is_none_or(|s| s.enabled);

    // Extract quotas
    let mut lo = vec![0usize; num_teachers];
    let mut hi = vec![0usize; num_teachers];
    let mut quota = vec![0.0f64; num_teachers];

    for tq in &report.quotas {
        if let Some(&idx) = teacher_id_to_idx.get(&tq.teacher_id) {
            lo[idx] = tq.lo;
            hi[idx] = tq.hi;
            quota[idx] = tq.quota;
        }
    }

    // Panels list and mapping
    let mut panel_keys = Vec::with_capacity(total_panels);
    let mut panel_exam_idx = Vec::with_capacity(total_panels);
    let mut panel_grade_idx = Vec::with_capacity(total_panels);

    for exam in &problem.exams {
        let e_idx = exam_id_to_idx[&exam.id];
        for grade in &problem.grades {
            let g_idx = grade_id_to_idx[&grade.id];
            panel_keys.push(PanelKey::new(exam.id, grade.id));
            panel_exam_idx.push(e_idx);
            panel_grade_idx.push(g_idx);
        }
    }

    // Teacher grades set
    let teacher_grades_set: HashSet<(usize, usize)> = problem
        .teacher_grades
        .iter()
        .filter(|tg| tg.school_year_id == problem.school_year.id)
        .filter_map(|tg| {
            let t_idx = teacher_id_to_idx.get(&tg.teacher_id)?;
            let g_idx = grade_id_to_idx.get(&tg.grade_id)?;
            Some((*t_idx, *g_idx))
        })
        .collect();

    // Teacher unavailabilities
    let unavailability_set: HashSet<(usize, usize)> = problem
        .unavailabilities
        .iter()
        .filter_map(|u| {
            let t_idx = teacher_id_to_idx.get(&u.teacher_id)?;
            let e_idx = exam_id_to_idx.get(&u.exam_id)?;
            Some((*t_idx, *e_idx))
        })
        .collect();

    // FORBID locks
    let mut forbid_any: HashSet<(usize, usize, usize)> = HashSet::new();
    let mut forbid_role: HashMap<(usize, usize, usize), HashSet<Role>> = HashMap::new();

    // PIN locks per panel
    let mut panel_pinned_setters: Vec<Vec<usize>> = vec![Vec::new(); total_panels];
    let mut panel_pinned_reviewers: Vec<Vec<usize>> = vec![Vec::new(); total_panels];
    let mut panel_pinned_any: Vec<Vec<usize>> = vec![Vec::new(); total_panels];

    for lock in &problem.locks {
        let e_idx = match exam_id_to_idx.get(&lock.exam_id) {
            Some(&idx) => idx,
            None => continue,
        };
        let g_idx = match grade_id_to_idx.get(&lock.grade_id) {
            Some(&idx) => idx,
            None => continue,
        };
        let t_idx = match teacher_id_to_idx.get(&lock.teacher_id) {
            Some(&idx) => idx,
            None => continue,
        };

        let p_idx = e_idx * num_grades + g_idx;

        match lock.kind {
            LockKind::Forbid => {
                let key = (e_idx, g_idx, t_idx);
                match lock.role {
                    None => {
                        forbid_any.insert(key);
                    }
                    Some(r) => {
                        forbid_role.entry(key).or_default().insert(r);
                    }
                }
            }
            LockKind::Pin => match lock.role {
                Some(Role::Setter) => panel_pinned_setters[p_idx].push(t_idx),
                Some(Role::Reviewer) => panel_pinned_reviewers[p_idx].push(t_idx),
                None => panel_pinned_any[p_idx].push(t_idx),
            },
        }
    }

    let is_eligible = |t: usize, e: usize, g: usize, role: Role| -> bool {
        let teacher = &problem.teachers[t];
        if !teacher.active || teacher.load_weight <= 0.0 || hi[t] == 0 {
            return false;
        }
        if !teacher_grades_set.contains(&(t, g)) {
            return false;
        }
        if unavailability_set.contains(&(t, e)) {
            return false;
        }
        let fkey = (e, g, t);
        if forbid_any.contains(&fkey) {
            return false;
        }
        if let Some(roles) = forbid_role.get(&fkey) {
            if roles.contains(&role) {
                return false;
            }
        }
        true
    };

    // Precompute candidate triples for each panel
    let mut static_triples: Vec<Vec<CandidateTriple>> = vec![Vec::new(); total_panels];
    let mut teacher_can_join_panel: Vec<Vec<bool>> = vec![vec![false; total_panels]; num_teachers];

    for p in 0..total_panels {
        let e = panel_exam_idx[p];
        let g = panel_grade_idx[p];

        let mut eligible_setters = Vec::new();
        let mut eligible_reviewers = Vec::new();

        for (t, can_join) in teacher_can_join_panel
            .iter_mut()
            .enumerate()
            .take(num_teachers)
        {
            let s = is_eligible(t, e, g, Role::Setter);
            let r = is_eligible(t, e, g, Role::Reviewer);
            if s {
                eligible_setters.push(t);
            }
            if r {
                eligible_reviewers.push(t);
            }
            if s || r {
                can_join[p] = true;
            }
        }

        let pinned_s = &panel_pinned_setters[p];
        let pinned_r = &panel_pinned_reviewers[p];
        let pinned_any = &panel_pinned_any[p];

        for &r in &eligible_reviewers {
            if !pinned_r.is_empty() && !pinned_r.contains(&r) {
                continue;
            }

            for (i, &s1) in eligible_setters.iter().enumerate() {
                if s1 == r {
                    continue;
                }
                for &s2 in &eligible_setters[i + 1..] {
                    if s2 == r {
                        continue;
                    }

                    // Campuses
                    let c1 = teacher_campuses[s1];
                    let c2 = teacher_campuses[s2];
                    let c3 = teacher_campuses[r];
                    if c1 == c2 && c1 == c3 {
                        continue;
                    }

                    // Check PIN requirements
                    if !pinned_s.is_empty() {
                        let has_all_s = pinned_s.iter().all(|&ps| ps == s1 || ps == s2);
                        if !has_all_s {
                            continue;
                        }
                    }

                    if !pinned_any.is_empty() {
                        let has_all_any =
                            pinned_any.iter().all(|&pa| pa == s1 || pa == s2 || pa == r);
                        if !has_all_any {
                            continue;
                        }
                    }

                    static_triples[p].push(CandidateTriple { s1, s2, r });
                }
            }
        }
    }

    // Verify static feasibility
    for p in 0..total_panels {
        if static_triples[p].is_empty() {
            return Err(SolveError::Exhausted {
                stats: SolveStats::default(),
                unfilled_panels: vec![panel_keys[p]],
            });
        }
    }

    // Solver state
    let mut rng = ChaCha8Rng::seed_from_u64(opts.seed);
    let mut assigned: Vec<Option<CandidateTriple>> = vec![None; total_panels];
    let mut used_count: Vec<usize> = vec![0; num_teachers];
    let mut exam_used: Vec<TeacherBitSet> = vec![TeacherBitSet::new(); num_exams];
    let mut unfilled: Vec<usize> = (0..total_panels).collect();

    let mut stats = SolveStats::default();
    let mut best_partial_count = 0usize;
    let mut best_partial_assignments: Vec<Assignment> = Vec::new();

    let res = backtrack(
        &mut assigned,
        &mut unfilled,
        &mut used_count,
        &mut exam_used,
        &static_triples,
        &teacher_can_join_panel,
        &panel_exam_idx,
        &panel_keys,
        &problem.teachers,
        &lo,
        &hi,
        &quota,
        h4_enabled,
        &mut rng,
        opts,
        start_time,
        &mut stats,
        &mut best_partial_count,
        &mut best_partial_assignments,
    );

    stats.elapsed_ms = start_time.elapsed().as_millis() as u64;

    match res {
        Ok(()) => {
            let mut assignments = Vec::with_capacity(total_panels * 3);
            for p in 0..total_panels {
                if let Some(triple) = assigned[p] {
                    let key = panel_keys[p];
                    assignments.push(Assignment::new(
                        key.exam_id,
                        key.grade_id,
                        problem.teachers[triple.s1].id,
                        Role::Setter,
                    ));
                    assignments.push(Assignment::new(
                        key.exam_id,
                        key.grade_id,
                        problem.teachers[triple.s2].id,
                        Role::Setter,
                    ));
                    assignments.push(Assignment::new(
                        key.exam_id,
                        key.grade_id,
                        problem.teachers[triple.r].id,
                        Role::Reviewer,
                    ));
                }
            }
            Ok(Solution {
                assignments,
                seed: opts.seed,
                stats,
            })
        }
        Err(err) => match err {
            SearchError::Exhausted => {
                let unfilled_panels = unfilled.iter().map(|&p| panel_keys[p]).collect();
                Err(SolveError::Exhausted {
                    stats,
                    unfilled_panels,
                })
            }
            SearchError::LimitReached => Err(SolveError::LimitReached {
                stats,
                best_partial: best_partial_assignments,
            }),
        },
    }
}

enum SearchError {
    Exhausted,
    LimitReached,
}

#[allow(clippy::too_many_arguments)]
fn backtrack(
    assigned: &mut [Option<CandidateTriple>],
    unfilled: &mut Vec<usize>,
    used_count: &mut [usize],
    exam_used: &mut [TeacherBitSet],
    static_triples: &[Vec<CandidateTriple>],
    teacher_can_join: &[Vec<bool>],
    panel_exam: &[usize],
    panel_keys: &[PanelKey],
    teachers: &[crate::domain::Teacher],
    lo: &[usize],
    hi: &[usize],
    quota: &[f64],
    h4: bool,
    rng: &mut ChaCha8Rng,
    opts: &SolveOptions,
    start_time: Instant,
    stats: &mut SolveStats,
    best_partial_count: &mut usize,
    best_partial: &mut Vec<Assignment>,
) -> Result<(), SearchError> {
    stats.nodes += 1;

    // Check limits periodically
    if stats.nodes.is_multiple_of(256)
        && (start_time.elapsed().as_millis() >= opts.time_limit_ms as u128
            || stats.nodes >= opts.max_nodes)
    {
        return Err(SearchError::LimitReached);
    }

    let assigned_count = assigned.len() - unfilled.len();
    if assigned_count > *best_partial_count {
        *best_partial_count = assigned_count;
        best_partial.clear();
        for p in 0..assigned.len() {
            if let Some(triple) = assigned[p] {
                let key = panel_keys[p];
                best_partial.push(Assignment::new(
                    key.exam_id,
                    key.grade_id,
                    teachers[triple.s1].id,
                    Role::Setter,
                ));
                best_partial.push(Assignment::new(
                    key.exam_id,
                    key.grade_id,
                    teachers[triple.s2].id,
                    Role::Setter,
                ));
                best_partial.push(Assignment::new(
                    key.exam_id,
                    key.grade_id,
                    teachers[triple.r].id,
                    Role::Reviewer,
                ));
            }
        }
    }

    if unfilled.is_empty() {
        // All panels filled! Check lower bounds
        for t in 0..used_count.len() {
            if used_count[t] < lo[t] {
                return Err(SearchError::Exhausted);
            }
        }
        return Ok(());
    }

    // MRV heuristic: find unfilled panel with fewest valid triples
    let mut best_panel_idx_in_unfilled = 0;
    let mut min_valid_triples = usize::MAX;
    let mut best_valid_triples: Vec<CandidateTriple> = Vec::new();

    for (ui, &p) in unfilled.iter().enumerate() {
        let e = panel_exam[p];
        let mut valid_triples = Vec::new();

        for &triple in &static_triples[p] {
            if h4
                && (exam_used[e].contains(triple.s1)
                    || exam_used[e].contains(triple.s2)
                    || exam_used[e].contains(triple.r))
            {
                continue;
            }
            if used_count[triple.s1] >= hi[triple.s1]
                || used_count[triple.s2] >= hi[triple.s2]
                || used_count[triple.r] >= hi[triple.r]
            {
                continue;
            }
            valid_triples.push(triple);
        }

        if valid_triples.is_empty() {
            // Immediate dead end!
            stats.backtracks += 1;
            return Err(SearchError::Exhausted);
        }

        if valid_triples.len() < min_valid_triples {
            min_valid_triples = valid_triples.len();
            best_panel_idx_in_unfilled = ui;
            best_valid_triples = valid_triples;
            if min_valid_triples == 1 {
                break; // Minimum possible
            }
        }
    }

    let chosen_p = unfilled.remove(best_panel_idx_in_unfilled);
    let chosen_e = panel_exam[chosen_p];

    // Value ordering: score triples by how far teachers are below quota, plus random jitter
    let mut scored_triples: Vec<(i64, CandidateTriple)> = best_valid_triples
        .into_iter()
        .map(|triple| {
            let deficit = (quota[triple.s1] - used_count[triple.s1] as f64)
                + (quota[triple.s2] - used_count[triple.s2] as f64)
                + (quota[triple.r] - used_count[triple.r] as f64);
            let jitter = (rng.next_u32() % 1000) as f64 / 10000.0;
            let score = ((deficit + jitter) * 10000.0) as i64;
            (score, triple)
        })
        .collect();

    // Sort descending by score
    scored_triples.sort_by_key(|a| std::cmp::Reverse(a.0));

    for (_, triple) in scored_triples {
        // Place triple
        assigned[chosen_p] = Some(triple);
        used_count[triple.s1] += 1;
        used_count[triple.s2] += 1;
        used_count[triple.r] += 1;

        if h4 {
            exam_used[chosen_e].insert(triple.s1);
            exam_used[chosen_e].insert(triple.s2);
            exam_used[chosen_e].insert(triple.r);
        }

        // Forward checking:
        // 1. Lower bounds reachable
        let remaining_slots = unfilled.len() * 3;
        let mut total_needed_lo = 0usize;
        let mut lo_feasible = true;

        for t in 0..used_count.len() {
            let needed = lo[t].saturating_sub(used_count[t]);
            total_needed_lo += needed;

            if needed > 0 {
                let available_panels = unfilled
                    .iter()
                    .filter(|&&up| {
                        teacher_can_join[t][up] && (!h4 || !exam_used[panel_exam[up]].contains(t))
                    })
                    .count();

                if available_panels < needed {
                    lo_feasible = false;
                    break;
                }
            }
        }

        if lo_feasible && total_needed_lo <= remaining_slots {
            // 2. Every remaining unfilled panel has at least one valid triple
            let mut all_panels_have_triple = true;
            for &up in unfilled.iter() {
                let ue = panel_exam[up];
                let has_valid = static_triples[up].iter().any(|t| {
                    if h4
                        && (exam_used[ue].contains(t.s1)
                            || exam_used[ue].contains(t.s2)
                            || exam_used[ue].contains(t.r))
                    {
                        return false;
                    }
                    used_count[t.s1] < hi[t.s1]
                        && used_count[t.s2] < hi[t.s2]
                        && used_count[t.r] < hi[t.r]
                });

                if !has_valid {
                    all_panels_have_triple = false;
                    break;
                }
            }

            if all_panels_have_triple {
                let sub_res = backtrack(
                    assigned,
                    unfilled,
                    used_count,
                    exam_used,
                    static_triples,
                    teacher_can_join,
                    panel_exam,
                    panel_keys,
                    teachers,
                    lo,
                    hi,
                    quota,
                    h4,
                    rng,
                    opts,
                    start_time,
                    stats,
                    best_partial_count,
                    best_partial,
                );

                if sub_res.is_ok() {
                    return Ok(());
                }
                if let Err(SearchError::LimitReached) = sub_res {
                    return Err(SearchError::LimitReached);
                }
            }
        }

        // Unplace triple (backtrack)
        stats.backtracks += 1;
        assigned[chosen_p] = None;
        used_count[triple.s1] -= 1;
        used_count[triple.s2] -= 1;
        used_count[triple.r] -= 1;

        if h4 {
            exam_used[chosen_e].remove(triple.s1);
            exam_used[chosen_e].remove(triple.s2);
            exam_used[chosen_e].remove(triple.r);
        }
    }

    // Restore chosen_p to unfilled
    unfilled.push(chosen_p);
    Err(SearchError::Exhausted)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::domain::{
        Campus, CampusId, Exam, ExamId, Grade, GradeId, Lock, LockId, Role, RuleSetting,
        SchoolYear, SchoolYearId, Teacher, TeacherGrade,
    };
    use crate::validate::{validate_assignments, ValidateOptions};

    fn make_seed_demo_problem() -> Problem {
        let sy = SchoolYear {
            id: SchoolYearId(1),
            name: "2026-2027".to_string(),
            is_current: true,
        };

        let campuses = vec![
            Campus {
                id: CampusId(1),
                code: "CS1".to_string(),
                name: "Cơ sở 1".to_string(),
                color: "#1e40af".to_string(),
            },
            Campus {
                id: CampusId(2),
                code: "CS2".to_string(),
                name: "Cơ sở 2".to_string(),
                color: "#059669".to_string(),
            },
            Campus {
                id: CampusId(3),
                code: "CS3".to_string(),
                name: "Cơ sở 3".to_string(),
                color: "#d97706".to_string(),
            },
            Campus {
                id: CampusId(4),
                code: "CS4".to_string(),
                name: "Cơ sở 4".to_string(),
                color: "#dc2626".to_string(),
            },
        ];

        let grades = vec![
            Grade {
                id: GradeId(1),
                code: 10,
                name: "Khối 10".to_string(),
                sort_order: 1,
            },
            Grade {
                id: GradeId(2),
                code: 11,
                name: "Khối 11".to_string(),
                sort_order: 2,
            },
            Grade {
                id: GradeId(3),
                code: 12,
                name: "Khối 12".to_string(),
                sort_order: 3,
            },
        ];

        let exams = vec![
            Exam {
                id: ExamId(1),
                school_year_id: sy.id,
                code: "GK1".to_string(),
                name: "Giữa kỳ 1".to_string(),
                sort_order: 1,
            },
            Exam {
                id: ExamId(2),
                school_year_id: sy.id,
                code: "CK1".to_string(),
                name: "Cuối kỳ 1".to_string(),
                sort_order: 2,
            },
            Exam {
                id: ExamId(3),
                school_year_id: sy.id,
                code: "GK2".to_string(),
                name: "Giữa kỳ 2".to_string(),
                sort_order: 3,
            },
            Exam {
                id: ExamId(4),
                school_year_id: sy.id,
                code: "CK2".to_string(),
                name: "Cuối kỳ 2".to_string(),
                sort_order: 4,
            },
        ];

        let teachers = vec![
            Teacher {
                id: TeacherId(1),
                full_name: "Nguyễn Văn An".to_string(),
                campus_id: CampusId(1),
                load_weight: 1.0,
                active: true,
                note: None,
            },
            Teacher {
                id: TeacherId(2),
                full_name: "Trần Thị Bình".to_string(),
                campus_id: CampusId(1),
                load_weight: 1.0,
                active: true,
                note: None,
            },
            Teacher {
                id: TeacherId(3),
                full_name: "Lê Hoàng Cường".to_string(),
                campus_id: CampusId(2),
                load_weight: 1.0,
                active: true,
                note: None,
            },
            Teacher {
                id: TeacherId(4),
                full_name: "Phạm Minh Đức".to_string(),
                campus_id: CampusId(2),
                load_weight: 1.0,
                active: true,
                note: None,
            },
            Teacher {
                id: TeacherId(5),
                full_name: "Hoàng Thu Giang".to_string(),
                campus_id: CampusId(3),
                load_weight: 1.0,
                active: true,
                note: None,
            },
            Teacher {
                id: TeacherId(6),
                full_name: "Vũ Hải Hà".to_string(),
                campus_id: CampusId(3),
                load_weight: 0.5,
                active: true,
                note: Some("Bán thời gian".to_string()),
            },
            Teacher {
                id: TeacherId(7),
                full_name: "Đặng Quốc Hùng".to_string(),
                campus_id: CampusId(3),
                load_weight: 1.0,
                active: true,
                note: None,
            },
            Teacher {
                id: TeacherId(8),
                full_name: "Bùi Thị Lan".to_string(),
                campus_id: CampusId(4),
                load_weight: 1.0,
                active: true,
                note: None,
            },
            Teacher {
                id: TeacherId(9),
                full_name: "Đỗ Tuấn Minh".to_string(),
                campus_id: CampusId(4),
                load_weight: 1.0,
                active: true,
                note: None,
            },
            Teacher {
                id: TeacherId(10),
                full_name: "Ngô Phương Nam".to_string(),
                campus_id: CampusId(1),
                load_weight: 1.0,
                active: true,
                note: None,
            },
            Teacher {
                id: TeacherId(11),
                full_name: "Dương Thùy Trang".to_string(),
                campus_id: CampusId(2),
                load_weight: 1.0,
                active: true,
                note: None,
            },
        ];

        let tg_tuples = [
            (1, 1),
            (3, 1),
            (5, 1),
            (8, 1), // Grade 10: T1, T3, T5, T8
            (2, 2),
            (4, 2),
            (6, 2),
            (9, 2),
            (1, 2), // Grade 11: T2, T4, T6, T9, T1
            (3, 3),
            (7, 3),
            (10, 3),
            (11, 3), // Grade 12: T3, T7, T10, T11
        ];

        let teacher_grades = tg_tuples
            .into_iter()
            .map(|(t, g)| TeacherGrade {
                teacher_id: TeacherId(t),
                school_year_id: sy.id,
                grade_id: GradeId(g),
            })
            .collect();

        let unavailabilities = vec![crate::domain::Unavailability {
            teacher_id: TeacherId(6),
            exam_id: ExamId(3),
            reason: Some("Khám sức khỏe".to_string()),
        }];

        Problem {
            school_year: sy,
            campuses,
            grades,
            exams,
            teachers,
            teacher_grades,
            unavailabilities,
            locks: vec![],
            rule_settings: RuleSetting::default_settings(),
        }
    }

    #[test]
    fn test_solve_demo_seed_returns_valid_solution() {
        let problem = make_seed_demo_problem();
        let opts = SolveOptions {
            seed: 42,
            time_limit_ms: 2000,
            max_nodes: 500_000,
        };

        let result = solve_hard(&problem, &opts);
        assert!(result.is_ok(), "solve_hard failed: {:?}", result.err());

        let solution = result.unwrap();
        assert_eq!(solution.assignments.len(), 36);

        // Validate complete solution
        let violations = validate_assignments(
            &problem,
            &solution.assignments,
            &ValidateOptions {
                require_complete: true,
            },
        );
        assert!(
            violations.is_empty(),
            "returned solution has violations: {violations:?}"
        );
    }

    #[test]
    fn test_solver_determinism_and_multi_seed_variation() {
        let problem = make_seed_demo_problem();

        let opts1 = SolveOptions {
            seed: 12345,
            ..Default::default()
        };
        let sol1a = solve_hard(&problem, &opts1).expect("sol1a");
        let sol1b = solve_hard(&problem, &opts1).expect("sol1b");
        assert_eq!(
            sol1a.assignments, sol1b.assignments,
            "same seed must produce identical assignments"
        );

        let opts2 = SolveOptions {
            seed: 98765,
            ..Default::default()
        };
        let sol2 = solve_hard(&problem, &opts2).expect("sol2");
        assert_ne!(
            sol1a.assignments, sol2.assignments,
            "different seeds should produce distinct assignments"
        );
    }

    #[test]
    fn test_solver_stops_early_on_infeasible_problem() {
        let mut problem = make_seed_demo_problem();
        // Conflicting PIN + FORBID
        problem.locks.push(Lock {
            id: LockId(1),
            exam_id: ExamId(1),
            grade_id: GradeId(1),
            teacher_id: TeacherId(1),
            role: Some(Role::Setter),
            kind: LockKind::Pin,
        });
        problem.locks.push(Lock {
            id: LockId(2),
            exam_id: ExamId(1),
            grade_id: GradeId(1),
            teacher_id: TeacherId(1),
            role: None,
            kind: LockKind::Forbid,
        });

        let opts = SolveOptions::default();
        let res = solve_hard(&problem, &opts);
        assert!(matches!(res, Err(SolveError::Infeasible { .. })));
    }

    fn brute_force_has_solution(problem: &Problem) -> bool {
        let panels: Vec<(ExamId, GradeId)> = problem
            .exams
            .iter()
            .flat_map(|e| problem.grades.iter().map(move |g| (e.id, g.id)))
            .collect();

        let teachers: Vec<TeacherId> = problem.teachers.iter().map(|t| t.id).collect();
        let n = teachers.len();

        let mut candidate_panels: Vec<Vec<Vec<Assignment>>> = Vec::new();
        for &(eid, gid) in &panels {
            let mut list = Vec::new();
            for i in 0..n {
                for j in (i + 1)..n {
                    for k in 0..n {
                        if k == i || k == j {
                            continue;
                        }
                        let assigns = vec![
                            Assignment::new(eid, gid, teachers[i], Role::Setter),
                            Assignment::new(eid, gid, teachers[j], Role::Setter),
                            Assignment::new(eid, gid, teachers[k], Role::Reviewer),
                        ];
                        let v = validate_assignments(
                            problem,
                            &assigns,
                            &ValidateOptions {
                                require_complete: false,
                            },
                        );
                        if v.is_empty() {
                            list.push(assigns);
                        }
                    }
                }
            }
            candidate_panels.push(list);
        }

        fn search(
            idx: usize,
            candidate_panels: &[Vec<Vec<Assignment>>],
            current: &mut Vec<Assignment>,
            problem: &Problem,
        ) -> bool {
            if idx == candidate_panels.len() {
                return validate_assignments(
                    problem,
                    current,
                    &ValidateOptions {
                        require_complete: true,
                    },
                )
                .is_empty();
            }

            for panel_assigns in &candidate_panels[idx] {
                let start_len = current.len();
                current.extend_from_slice(panel_assigns);
                let v = validate_assignments(
                    problem,
                    current,
                    &ValidateOptions {
                        require_complete: false,
                    },
                );
                if v.is_empty() && search(idx + 1, candidate_panels, current, problem) {
                    return true;
                }
                current.truncate(start_len);
            }
            false
        }

        let mut current = Vec::new();
        search(0, &candidate_panels, &mut current, problem)
    }

    #[test]
    fn test_exhaustive_cross_check_tiny_instances() {
        let mut rng = ChaCha8Rng::seed_from_u64(20261002);
        let num_instances = 300;

        let mut feasible_count = 0;
        let mut infeasible_count = 0;
        let mut backtrack_count = 0;

        for instance_idx in 0..num_instances {
            let sy = SchoolYear {
                id: SchoolYearId(1),
                name: "2026-2027".to_string(),
                is_current: true,
            };
            let c1 = Campus {
                id: CampusId(1),
                code: "C1".to_string(),
                name: "C1".to_string(),
                color: "#000".to_string(),
            };
            let c2 = Campus {
                id: CampusId(2),
                code: "C2".to_string(),
                name: "C2".to_string(),
                color: "#fff".to_string(),
            };
            let g1 = Grade {
                id: GradeId(1),
                code: 10,
                name: "G10".to_string(),
                sort_order: 1,
            };
            let g2 = Grade {
                id: GradeId(2),
                code: 11,
                name: "G11".to_string(),
                sort_order: 2,
            };
            let e1 = Exam {
                id: ExamId(1),
                school_year_id: sy.id,
                code: "GK".to_string(),
                name: "GK".to_string(),
                sort_order: 1,
            };

            // Tight instance setup: 6 teachers, 2 campuses.
            // Under H4 and 2 panels in 1 exam, all 6 teachers must be assigned (3 in P1, 3 in P2).
            let mut teachers = Vec::new();
            let mut teacher_grades = Vec::new();

            for tid in 1..=6 {
                // Campuses: T1..T3 on C1, T4..T6 vary to create bottlenecks.
                let camp = if tid <= 3 {
                    CampusId(1)
                } else if tid == 4 {
                    if (rng.next_u32() % 10) < 6 {
                        CampusId(1)
                    } else {
                        CampusId(2)
                    }
                } else if tid == 5 {
                    CampusId(2)
                } else {
                    if (rng.next_u32() % 10) < 5 {
                        CampusId(2)
                    } else {
                        CampusId(1)
                    }
                };

                teachers.push(Teacher {
                    id: TeacherId(tid),
                    full_name: format!("T{tid}"),
                    campus_id: camp,
                    load_weight: 1.0,
                    active: true,
                    note: None,
                });

                // Qualifications: T1..T3 more likely G1, T4..T6 more likely G2
                let p1 = if tid <= 2 {
                    9
                } else if tid <= 4 {
                    6
                } else {
                    3
                };
                let p2 = if tid >= 4 {
                    9
                } else if tid >= 2 {
                    6
                } else {
                    3
                };

                if (rng.next_u32() % 10) < p1 {
                    teacher_grades.push(TeacherGrade {
                        teacher_id: TeacherId(tid),
                        school_year_id: sy.id,
                        grade_id: GradeId(1),
                    });
                }
                if (rng.next_u32() % 10) < p2 {
                    teacher_grades.push(TeacherGrade {
                        teacher_id: TeacherId(tid),
                        school_year_id: sy.id,
                        grade_id: GradeId(2),
                    });
                }
            }

            // Ensure every teacher has at least 1 grade so they don't trivially fail F1/F2
            for tid in 1..=6 {
                if !teacher_grades
                    .iter()
                    .any(|tg| tg.teacher_id == TeacherId(tid))
                {
                    let gid = if (rng.next_u32() % 2) == 0 {
                        GradeId(1)
                    } else {
                        GradeId(2)
                    };
                    teacher_grades.push(TeacherGrade {
                        teacher_id: TeacherId(tid),
                        school_year_id: sy.id,
                        grade_id: gid,
                    });
                }
            }

            // Locks: occasional PIN or FORBID lock
            let mut locks = Vec::new();
            if (rng.next_u32() % 10) < 4 {
                let lock_tid = TeacherId((rng.next_u32() % 6 + 1) as i64);
                let lock_gid = if (rng.next_u32() % 2) == 0 {
                    GradeId(1)
                } else {
                    GradeId(2)
                };
                let kind = if (rng.next_u32() % 2) == 0 {
                    LockKind::Pin
                } else {
                    LockKind::Forbid
                };
                locks.push(Lock {
                    id: LockId(1),
                    exam_id: ExamId(1),
                    grade_id: lock_gid,
                    teacher_id: lock_tid,
                    role: Some(Role::Setter),
                    kind,
                });
            }

            // Rule settings: with 50% chance, enforce strict tolerance k = 0
            let mut rule_settings = RuleSetting::default_settings();
            if (rng.next_u32() % 2) == 0 {
                if let Some(h7) = rule_settings.iter_mut().find(|s| s.key == RuleKey::H7) {
                    h7.params = serde_json::json!({ "tolerance": 0 });
                }
            }

            let prob = Problem {
                school_year: sy,
                campuses: vec![c1, c2],
                grades: vec![g1, g2],
                exams: vec![e1],
                teachers,
                teacher_grades,
                unavailabilities: vec![],
                locks,
                rule_settings,
            };

            let opts = SolveOptions {
                seed: instance_idx as u64,
                time_limit_ms: 1000,
                max_nodes: 50_000,
            };

            let bf_feasible = brute_force_has_solution(&prob);
            let solver_res = solve_hard(&prob, &opts);

            match solver_res {
                Ok(sol) => {
                    assert!(
                        bf_feasible,
                        "Instance {instance_idx}: Solver found solution but brute force reported infeasible!"
                    );
                    let v = validate_assignments(
                        &prob,
                        &sol.assignments,
                        &ValidateOptions {
                            require_complete: true,
                        },
                    );
                    assert!(
                        v.is_empty(),
                        "Instance {instance_idx} produced violations: {v:?}"
                    );
                    feasible_count += 1;
                    if sol.stats.backtracks > 0 {
                        backtrack_count += 1;
                    }
                }
                Err(_) => {
                    assert!(
                        !bf_feasible,
                        "Instance {instance_idx}: Brute force found solution but solver reported infeasible!"
                    );
                    infeasible_count += 1;
                }
            }
        }

        let backtrack_pct = (backtrack_count as f64 / feasible_count as f64) * 100.0;
        println!(
            "Cross-check: {num_instances} instances tested | Feasible: {feasible_count}, Infeasible: {infeasible_count} | Backtracked: {backtrack_count} ({backtrack_pct:.1}% of feasible)"
        );
        assert_eq!(feasible_count + infeasible_count, num_instances);
        assert!(
            backtrack_pct >= 20.0,
            "Expected >= 20% backtracks among feasible instances, got {backtrack_pct:.1}%"
        );
    }

    #[test]
    fn test_performance_timing_demo_seed() {
        let problem = make_seed_demo_problem();
        let opts = SolveOptions {
            seed: 42,
            time_limit_ms: 2000,
            max_nodes: 500_000,
        };

        let start = Instant::now();
        let sol = solve_hard(&problem, &opts).expect("demo solve");
        let elapsed = start.elapsed();

        println!(
            "Demo seed solve time: {:?} (nodes: {}, backtracks: {})",
            elapsed, sol.stats.nodes, sol.stats.backtracks
        );
        // Target: < 50ms (in debug mode on CI it might be slightly higher, but usually < 20ms)
        assert_eq!(sol.assignments.len(), 36);
    }

    #[test]
    fn test_performance_synthetic_40_teacher_instance() {
        let sy = SchoolYear {
            id: SchoolYearId(1),
            name: "2026-2027".to_string(),
            is_current: true,
        };

        let campuses: Vec<Campus> = (1..=6)
            .map(|c| Campus {
                id: CampusId(c),
                code: format!("CS{c}"),
                name: format!("Cơ sở {c}"),
                color: "#1e40af".to_string(),
            })
            .collect();

        let grades: Vec<Grade> = (1..=3)
            .map(|g| Grade {
                id: GradeId(g),
                code: (9 + g) as i32,
                name: format!("Khối {}", 9 + g),
                sort_order: g as i32,
            })
            .collect();

        let exams: Vec<Exam> = (1..=4)
            .map(|e| Exam {
                id: ExamId(e),
                school_year_id: sy.id,
                code: format!("EX{e}"),
                name: format!("Kỳ thi {e}"),
                sort_order: e as i32,
            })
            .collect();

        let mut teachers = Vec::with_capacity(40);
        let mut teacher_grades = Vec::new();

        for tid in 1..=40 {
            let cid = ((tid - 1) % 6) + 1;
            teachers.push(Teacher {
                id: TeacherId(tid),
                full_name: format!("Giáo viên {tid}"),
                campus_id: CampusId(cid),
                load_weight: 1.0,
                active: true,
                note: None,
            });

            // Each teacher teaches 1 or 2 grades
            let g1 = ((tid - 1) % 3) + 1;
            teacher_grades.push(TeacherGrade {
                teacher_id: TeacherId(tid),
                school_year_id: sy.id,
                grade_id: GradeId(g1),
            });
            if tid % 2 == 0 {
                let g2 = (g1 % 3) + 1;
                teacher_grades.push(TeacherGrade {
                    teacher_id: TeacherId(tid),
                    school_year_id: sy.id,
                    grade_id: GradeId(g2),
                });
            }
        }

        let problem = Problem {
            school_year: sy,
            campuses,
            grades,
            exams,
            teachers,
            teacher_grades,
            unavailabilities: vec![],
            locks: vec![],
            rule_settings: RuleSetting::default_settings(),
        };

        let opts = SolveOptions {
            seed: 777,
            time_limit_ms: 3000,
            max_nodes: 500_000,
        };

        let start = Instant::now();
        let sol = solve_hard(&problem, &opts).expect("synthetic 40-teacher solve");
        let elapsed = start.elapsed();

        println!(
            "Synthetic 40-teacher solve time: {:?} (nodes: {}, backtracks: {})",
            elapsed, sol.stats.nodes, sol.stats.backtracks
        );
        assert_eq!(sol.assignments.len(), 36);

        let violations = validate_assignments(
            &problem,
            &sol.assignments,
            &ValidateOptions {
                require_complete: true,
            },
        );
        assert!(violations.is_empty(), "violations: {violations:?}");
    }
}
