#!/usr/bin/env python3
"""Builds docs/qa/real-run-20261005-linux/FIX-STATUS.md from fix-status-src.json and git history.

Commits come from `git log --grep`, evidence paths are checked for existence and the summary
counts are computed here, so nothing in the report is typed by hand (Reporting Integrity Rule).
"""
import json, os, subprocess, sys, collections

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))
SRC = os.path.join(ROOT, 'scripts', 'qa', 'fix-status-src.json')
OUT = os.path.join(ROOT, 'docs', 'qa', 'real-run-20261005-linux', 'FIX-STATUS.md')
findings = {f['id']: f for f in json.load(open(os.path.join(ROOT, 'docs', 'qa', 'real-run-20261005-linux', 'findings.json')))}
src = json.load(open(SRC))


def commits(fid):
    out = subprocess.run(['git', 'log', '--format=%h', f'--grep={fid}\\b', '-E'], cwd=ROOT, capture_output=True, text=True).stdout.split()
    # `-E` + word boundary: avoid RA-01 matching RA-011 by anchoring on a non-digit
    return out


def commits_exact(fid):
    out = subprocess.run(['git', 'log', '--format=%h%x09%B%x00'], cwd=ROOT, capture_output=True, text=True).stdout
    hits = []
    import re
    pat = re.compile(r'\b' + re.escape(fid) + r'(?!\d)')
    for rec in out.split('\x00'):
        rec = rec.strip('\n')
        if not rec:
            continue
        h, _, body = rec.partition('\t')
        if pat.search(body):
            hits.append(h.strip())
    return list(reversed(hits))


rows, missing = [], []
counts = collections.Counter()
for fid in sorted(findings, key=lambda x: int(x.split('-')[1])):
    e = src[fid]
    c = commits_exact(fid) if e['status'] == 'fixed' else []
    ev = []
    ev_dir = os.path.join(ROOT, 'docs', 'reports', 'qa-fix', fid)
    auto = sorted(os.path.join('docs/reports/qa-fix', fid, f) for f in os.listdir(ev_dir)) if os.path.isdir(ev_dir) else []
    for p in auto + e.get('evidence', []):
        ok = os.path.exists(os.path.join(ROOT, p))
        ev.append(f'[{os.path.basename(p) if not os.path.isdir(os.path.join(ROOT, p)) else p}](../../../{p})' if ok else f'MISSING:{p}')
        if not ok:
            missing.append((fid, p))
    counts[e['status']] += 1
    rows.append((fid, findings[fid]['severity'], e['status'], ', '.join(f'`{x}`' for x in c) or '—', e.get('tests', '—'), '<br>'.join(ev) or '—', e.get('note', '')))

lines = ['# FIX-STATUS — status of every real-run finding (RA-001 … RA-043)', '',
         'Generated by `scripts/qa/fix_status.py` from `scripts/qa/fix-status-src.json`, `findings.json` and `git log`; the counts below are computed by the script, not typed.', '',
         '## Counts', '', '| Status | Count |', '|---|---|']
for st in ('fixed', 'wontfix', 'needs-decision', 'not-reproducible'):
    lines.append(f'| {st} | {counts.get(st, 0)} |')
lines.append(f'| **total** | {sum(counts.values())} |')
lines += ['', 'Evidence for each fix is under `docs/reports/qa-fix/<ID>/`: `before*.txt` is the regression test run on the unfixed code (it fails), `after*.txt` the same on the fixed code (it passes); `e2e-before-baseline-*.txt` / `e2e-after-*.txt` are runs of the real app (`e2e-real/`) on the unfixed (`main`) and fixed release builds.', '',
          '## Table', '', '| ID | Sev | Status | Commit(s) | Regression test(s) | Evidence | Note |', '|---|---|---|---|---|---|---|']
for r in rows:
    lines.append('| ' + ' | '.join(str(x).replace('|', '\\|') for x in r) + ' |')
open(OUT, 'w').write('\n'.join(lines) + '\n')
print(json.dumps(dict(counts), ensure_ascii=False))
if missing:
    print('MISSING EVIDENCE:', missing)
    sys.exit(1)
