import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const rootDir = path.resolve(__dirname, '..');
const reportsDir = path.join(rootDir, 'docs', 'reports');

/**
 * Parse raw `cargo test` output into structured test binary results.
 */
function parseCargoTestOutput(rawOutput) {
  const lines = rawOutput.split(/\r?\n/);
  const binaries = [];
  let currentBinary = null;

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];

    const runningMatch = line.match(/^\s*Running\s+(.+?)\s+\((.+?)\)$/);
    if (runningMatch) {
      const sourcePath = runningMatch[1].replace(/\\/g, '/');
      const binPath = runningMatch[2].replace(/\\/g, '/');
      const binFilename = path.basename(binPath);

      let crateName = 'unknown';
      if (binFilename.startsWith('exam_panel_core') || sourcePath.includes('crates/core')) {
        crateName = 'crates/core';
      } else if (
        binFilename.startsWith('exam_panel_storage') ||
        binFilename.startsWith('backup_tests') ||
        binFilename.startsWith('migration_tests') ||
        binFilename.startsWith('repository_tests') ||
        binFilename.startsWith('v4_migration_tests') ||
        sourcePath.includes('crates/storage')
      ) {
        crateName = 'crates/storage';
      } else if (
        binFilename.startsWith('exam_panel_service') ||
        binFilename.startsWith('excel_tests') ||
        binFilename.startsWith('part_b_tests') ||
        binFilename.startsWith('pipeline_report_test') ||
        binFilename.startsWith('service_tests') ||
        binFilename.startsWith('trial_mode_tests') ||
        binFilename.startsWith('generate_types') ||
        binFilename.startsWith('import_q_data') ||
        binFilename.startsWith('phase11_report') ||
        binFilename.startsWith('task5_comparison') ||
        binFilename.startsWith('task6_h3') ||
        binFilename.startsWith('task7_perf') ||
        binFilename.startsWith('generate_sample_excels') ||
        binFilename.startsWith('plan_import_tests') ||
        binFilename.startsWith('comparison_tests') ||
        binFilename.startsWith('warm_start_tests') ||
        binFilename.startsWith('generate_presets_report') ||
        sourcePath.includes('crates/service')
      ) {
        crateName = 'crates/service';
      } else if (binFilename.startsWith('exam_panel_app') || sourcePath.includes('src-tauri')) {
        crateName = 'src-tauri';
      }

      currentBinary = {
        crate: crateName,
        source: sourcePath,
        bin: binFilename,
        passed: 0,
        failed: 0,
        ignored: 0,
        finished: false,
      };
      binaries.push(currentBinary);
      continue;
    }

    const resultMatch = line.match(
      /test result: (\w+)\.\s+(\d+)\s+passed;\s+(\d+)\s+failed;\s+(\d+)\s+ignored;/
    );
    if (resultMatch && currentBinary) {
      currentBinary.passed = parseInt(resultMatch[2], 10);
      currentBinary.failed = parseInt(resultMatch[3], 10);
      currentBinary.ignored = parseInt(resultMatch[4], 10);
      currentBinary.status = resultMatch[1];
      currentBinary.finished = true;
      currentBinary = null;
    }
  }

  return binaries;
}

function stripAnsi(str) {
  return str.replace(/\x1b\[[0-9;]*[a-zA-Z]/g, '');
}

/**
 * Parse raw `ui-test.txt` output into total passed test count.
 */
function parseVitestOutput(rawOutput) {
  const clean = stripAnsi(rawOutput);
  const match = clean.match(/Tests\s+(\d+)\s+passed/);
  if (match) {
    return parseInt(match[1], 10);
  }
  return null;
}

function main() {
  const phaseDirs = [
    'phase-7',
    'phase-8',
    'phase-9',
    'phase-10',
    'phase-11',
    'phase-11.1',
    'phase-12',
    'phase-12.1',
  ];

  let output = '=== ExamPanel Historical Test Inventory & Reconciliation ===\n\n';
  output += 'Generated by scripts/test-history.mjs\n';
  output += 'Scanned directories: docs/reports/phase-*\n\n';

  output += '## 1. Per-Phase Test Counts Summary\n\n';
  output += '| Phase | Rust Core | Rust Storage | Rust Service | Rust Total | Vitest (UI) | Total Tests |\n';
  output += '|---|---|---|---|---|---|---|\n';

  const phaseData = [];

  for (const phase of phaseDirs) {
    const dir = path.join(reportsDir, phase);
    if (!fs.existsSync(dir)) continue;

    let coreCount = 0;
    let storageCount = 0;
    let serviceCount = 0;
    let rustTotal = 0;
    let vitestCount = 0;

    const cargoFile = path.join(dir, 'cargo-test.txt');
    if (fs.existsSync(cargoFile)) {
      const rawCargo = fs.readFileSync(cargoFile, 'utf-8');
      const binaries = parseCargoTestOutput(rawCargo);
      for (const b of binaries) {
        if (b.crate === 'crates/core') coreCount += b.passed;
        else if (b.crate === 'crates/storage') storageCount += b.passed;
        else if (b.crate === 'crates/service') serviceCount += b.passed;
      }
      rustTotal = coreCount + storageCount + serviceCount;
    }

    const uiFile = path.join(dir, 'ui-test.txt');
    if (fs.existsSync(uiFile)) {
      const rawUi = fs.readFileSync(uiFile, 'utf-8');
      const v = parseVitestOutput(rawUi);
      if (v !== null) vitestCount = v;
    }

    const total = rustTotal + vitestCount;
    output += `| ${phase} | ${coreCount} | ${storageCount} | ${serviceCount} | ${rustTotal} | ${vitestCount} | ${total} |\n`;

    phaseData.push({
      phase,
      coreCount,
      storageCount,
      serviceCount,
      rustTotal,
      vitestCount,
      total,
      cargoFileExists: fs.existsSync(cargoFile),
    });
  }

  output += '\n## 2. Detailed Per-Binary Breakdown by Phase\n\n';

  for (const item of phaseData) {
    output += `### ${item.phase}\n\n`;
    const cargoFile = path.join(reportsDir, item.phase, 'cargo-test.txt');
    if (fs.existsSync(cargoFile)) {
      const rawCargo = fs.readFileSync(cargoFile, 'utf-8');
      const binaries = parseCargoTestOutput(rawCargo);

      output += '| Crate | Source / Test Binary | Passed | Ignored | Status |\n';
      output += '|---|---|---|---|---|\n';
      for (const b of binaries) {
        output += `| ${b.crate} | ${b.source} | ${b.passed} | ${b.ignored} | ${b.status || 'ok'} |\n`;
      }
      output += `\n**Vitest UI Tests:** ${item.vitestCount} passed\n\n`;
    } else {
      output += `(No cargo-test.txt found for ${item.phase})\n\n`;
    }
  }

  output += '## 3. Discrepancy Reconciliation & Historical Clarifications\n\n';
  output += '- **Phase 9 Inventory Reconciliation:**\n';
  output += '  - The Phase 9 narrative report loosely referred to "76 core / 23 storage / 49 vitest", whereas the actual Phase 9 committed artifacts record:\n';
  output += '    - `cargo-test.txt`: `crates/core`: 75 passed (77 defined, 2 ignored benches), `crates/storage`: 26 passed (4 unit + 6 migration + 4 repository + 12 backup), `crates/service`: 20 passed. Total Rust: 121 passed.\n';
  output += '    - `ui-test.txt`: 62 passed tests (49 was an earlier pre-backup count before `BackupSection.test.tsx` and `PrintPages.test.tsx` were added in Phase 9).\n';
  output += '- **Script Name Clarification:**\n';
  output += '  - The Phase 12 report cited `test-inventory.sh`; the canonical repository script is `scripts/test-inventory.mjs` (Node ESM).\n';
  output += '- **Phase 12 vs 12.1 UI Expansion:**\n';
  output += '  - Phase 11.1 had 69 Vitest tests.\n';
  output += '  - Phase 12 reported 77 tests (+8 tests).\n';
  output += '  - Phase 12.1 completes the grid editing and interaction coverage (`ui/src/pages/assignments/GridEditing.test.tsx`) bringing Vitest tests to 86 passed (+9 comprehensive tests covering seat click candidate list with reasons, drag-to-swap, keyboard flow, undo/redo, forced seats immovable, totals panel markers, teacher hover focus, view-toggle persistence, two-subject layout with blank CN second "Đề" row).\n';

  const destPath = path.join(reportsDir, 'phase-12.1', 'test-history.txt');
  fs.writeFileSync(destPath, output, 'utf-8');
  console.log(`Successfully generated ${destPath}`);
}

main();
