import { prepareRunDir, withApp, sleep, OUT_ABS } from '../lib/harness.mjs';
import { recorder } from '../lib/rec.mjs';
import { sha256, sql } from '../lib/native.mjs';
import { clickTid, bodyText, tid } from '../lib/ui.mjs';
import fs from 'node:fs'; import path from 'node:path';
const R = recorder('B1');
import { execSync } from 'node:child_process';
const logicalHash = (f) => execSync(`sqlite3 ${f} .dump | grep -v 'INSERT INTO sqlite_sequence' | sha256sum`).toString().split(' ')[0];
const run = prepareRunDir('B1', { portable: true, seedDb: path.resolve('../.tools/golden/q-after-import.db') });
const db = path.join(run.dataDir, 'exam-panel.db');
const h0 = sha256(db); fs.copyFileSync(db, path.join(run.dir, 'out/db-0-before-launch.db'));
await withApp({ scenario: 'B1', run }, async (app) => {
  await sleep(1500); const hIdle = sha256(db); globalThis.__hIdle = hIdle; fs.copyFileSync(db, path.join(run.dir, 'out/db-1-idle.db')); R.check('B1.startup-does-not-modify-existing-db', hIdle === h0, { before_launch: h0, after_ready: hIdle }, 'identical sha256 (informational: startup may legitimately run seed_defaults/migrations)');
  await app.nav('/settings'); await sleep(1000);
  await clickTid(app.b, 'enter-trial-mode-btn'); await sleep(1500);
  const banner = await tid(app.b, 'trial-mode-banner'); const bannerShown = await banner.isExisting();
  R.check('B1.banner-visible', bannerShown, bannerShown ? await banner.getText() : null, 'amber banner', ['screenshots/B1-trial-page.png']);
  await app.shot('B1-trial');
  const teachers = await app.invoke('list_teachers', {});
  const subjects = await app.invoke('list_subjects', { schoolYearId: 1 });
  const info = await app.invoke('get_app_info');
  R.note('trial_info', info.v); const sy = (await app.invoke('list_school_years', {})).v.find((y) => y.is_current); R.note('trial_teachers', teachers.ok ? teachers.v.map((t) => t.display_name || t.full_name) : teachers); R.note('trial_subjects', subjects.ok ? subjects.v.map((s) => ({ code: s.code, setters: s.setters, reviewers: s.reviewers, min: s.min_campuses })) : subjects);
  R.check('B1.demo-is-Q-shaped-12-teachers', teachers.ok && teachers.v.length === 12, teachers.ok && teachers.v.length, '12 teachers (task); release checklist v0.1.0 says 18 teachers/2 campuses — stale?');
  R.check('B1.demo-subjects-VL-CN', subjects.ok && subjects.v.map((s) => s.code).sort().join() === 'CN,VL', subjects.ok && subjects.v.map((s) => s.code), 'VL + CN');
  R.check('B1.real-db-unchanged-while-in-trial', sha256(db) === hIdle, { idle: hIdle, now: sha256(db) }, 'identical sha256');
  await app.nav('/assignments'); await sleep(1500); await app.shot('B1-trial-assignments');
  await app.nav('/teachers'); await sleep(1000);
  // mutate in trial: deactivate+rename via IPC
  const t0 = teachers.v[0]; const upd = await app.invoke('update_teacher', { teacher: { ...t0, full_name: 'TRIAL-EDIT-' + t0.full_name } }).catch((e) => ({ err: String(e) }));
  R.note('trial_edit_result', upd);
  await clickTid(app.b, 'exit-trial-mode-btn').catch(async () => { await clickTid(app.b, 'exit-trial-btn'); });
  await sleep(1500);
  const back = await app.invoke('list_teachers', {});
  R.check('B1.exit-restores-real-data', back.ok && back.v.length === 12 && back.v.every((t) => !/TRIAL-EDIT/.test(t.full_name)), back.ok && back.v.map((t) => t.full_name), '12 real teachers, no trial edits');
  fs.copyFileSync(db, path.join(run.dir, 'out/db-2-after-exit.db')); const infoBack = await app.invoke('get_app_info'); R.note('after_exit_info', infoBack.v);
  await app.shot('B1-after-exit');
  const bannerGone = !(await (await tid(app.b, 'trial-mode-banner')).isExisting());
  R.check('B1.banner-gone-after-exit', bannerGone, bannerGone, 'banner hidden');
});
R.check('B1.real-db-bytes-after-exit', sha256(db) === globalThis.__hIdle, { idle: globalThis.__hIdle, after: sha256(db) }, 'identical sha256 (task wording)');
R.check('B1.real-db-logical-content-after-exit', logicalHash(path.join(run.dir, 'out/db-1-idle.db')) === logicalHash(path.join(run.dir, 'out/db-2-after-exit.db')), { idle: logicalHash(path.join(run.dir, 'out/db-1-idle.db')), after: logicalHash(path.join(run.dir, 'out/db-2-after-exit.db')) }, 'identical .dump excluding sqlite_sequence');
R.note('byte_diff_cause', 'sqlite_sequence grades +3 on every open of the DB (diff of .dump): see logs/B1-dump-diff.txt');
fs.writeFileSync(path.join(OUT_ABS, 'logs/B1-dump-diff.txt'), execSync(`cd ${run.dir}/out; for f in db-0-before-launch db-1-idle db-2-after-exit; do sqlite3 $f.db .dump > /tmp/$f.sql; done; echo "== before-launch vs idle"; diff /tmp/db-0-before-launch.sql /tmp/db-1-idle.sql; echo "== idle vs after-exit"; diff /tmp/db-1-idle.sql /tmp/db-2-after-exit.sql; true`, {shell:'/bin/bash'}).toString());
const demo = path.join(run.dataDir, 'demo.db');
R.note('demo_db_exists', fs.existsSync(demo));
