import { prepareRunDir, launchApp, waitUiReady, sleep, OUT_ABS } from '../lib/harness.mjs';
import { recorder } from '../lib/rec.mjs';
import { driveFileDialog } from '../lib/native.mjs';
import { clickTid, bodyText } from '../lib/ui.mjs';
import fs from 'node:fs'; import path from 'node:path';
const R = recorder('B2');
const run = prepareRunDir('B2', { portable: true });
const app = await launchApp({ scenario: 'B2', run }); await waitUiReady(app);
await app.shot('B2-fresh-overview');
R.note('fresh_overview_text', (await bodyText(app.b)).slice(0, 1500));
await app.nav('/teachers'); await sleep(800);
await clickTid(app.b, 'download-template-btn');
const target = path.join(run.dir, 'out/mau-nhap-du-lieu.xlsx');
const r = await driveFileDialog(target, { shotName: 'B2-template-save-dialog' });
await sleep(800);
R.check('B2.template-download-dialog', r.ok && fs.existsSync(target), { r, size: fs.existsSync(target) && fs.statSync(target).size }, 'file saved at typed path', ['screenshots/B2-template-save-dialog.png']);
fs.copyFileSync(target, path.join(OUT_ABS, 'extracts/B2-template-downloaded.xlsx'));
fs.writeFileSync(path.join(run.dir, 'out/state.json'), JSON.stringify({ run: run.dir, template: target }));
await app.stop();
console.log(run.dir);
