import { prepareRunDir, launchApp, waitUiReady, sleep, OUT_ABS } from '../lib/harness.mjs';
import { recorder } from '../lib/rec.mjs';
import { driveFileDialog, sql, sha256 } from '../lib/native.mjs';
import { clickTid, bodyText, tid } from '../lib/ui.mjs';
import fs from 'node:fs'; import path from 'node:path';
const R = recorder('B2');
const run = prepareRunDir('B2golden', { portable: true });
const filled = path.join(OUT_ABS, 'extracts/B2-q-filled.xlsx');
fs.copyFileSync(filled, path.join(run.dir, 'out/q-filled.xlsx')); import('node:child_process').then(c => c.execSync(`chown -R qauser:qauser ${run.dir}`));
const db = path.join(run.dataDir, 'exam-panel.db');
const app = await launchApp({ scenario: 'B2', run }); await waitUiReady(app);
const before = { sha: sha256(db), counts: sql(db, "select (select count(*) from teachers) t,(select count(*) from campuses) c,(select count(*) from subjects) s") };
await app.nav('/teachers'); await sleep(800);
await clickTid(app.b, 'import-excel-btn'); await sleep(600);
await app.shot('B2-import-step1');
await clickTid(app.b, 'import-browse-btn');
const r = await driveFileDialog(path.join(run.dir, 'out/q-filled.xlsx'), { shotName: 'B2-import-open-dialog' });
R.check('B2.open-dialog-driven', r.ok, r, 'GTK open dialog accepts typed path', ['screenshots/B2-import-open-dialog.png']);
await sleep(600);
const pathShown = await app.b.execute(() => [...document.querySelectorAll('input')].map((i) => i.value).filter(Boolean));
R.note('inputs_after_browse', pathShown);
await clickTid(app.b, 'import-run-preview-btn'); await sleep(2500);
await app.shot('B2-import-preview');
const prevText = await bodyText(app.b); fs.writeFileSync(path.join(OUT_ABS, 'extracts/B2-preview-text.txt'), prevText);
R.note('preview_text_head', prevText.slice(0, 2500));
for (const tab of ['tab-campuses', 'tab-teachers']) { try { await clickTid(app.b, tab); await sleep(400); await app.shot('B2-preview-' + tab); } catch (e) { R.note('tab-fail-' + tab, e.message); } }
const canApply = await (await tid(app.b, 'import-apply-btn')).isEnabled().catch(() => null);
R.check('B2.preview-can-apply', canApply === true, canApply, 'apply button enabled', ['screenshots/B2-import-preview-page.png']);
const dbSameAfterPreview = sha256(db) === before.sha;
R.check('B2.preview-is-read-only', dbSameAfterPreview, { before: before.sha, after: sha256(db) }, 'DB unchanged by preview (ADR: strictly read-only preview)');
await clickTid(app.b, 'import-apply-btn'); await sleep(2500);
await app.shot('B2-import-applied');
const after = { counts: sql(db, "select (select count(*) from teachers) t,(select count(*) from campuses) c,(select count(*) from subjects) s,(select count(*) from teacher_competencies) comp,(select count(*) from teacher_grades) tg"), teachers: sql(db, 'select full_name,display_name,quota_override,max_tasks_per_exam_override,active from teachers order by id'), campuses: sql(db, 'select code,name from campuses'), subjects: sql(db, 'select code,name,setters,reviewers,min_campuses from subjects order by sort_order') };
R.note('after', after);
R.check('B2.teachers=12', after.counts[0].t === 12, after.counts[0], '12 teachers');
R.check('B2.one-campus-placeholder', after.campuses.length === 1 && after.campuses[0].name === 'Chưa phân hiệu', after.campuses, 'only "Chưa phân hiệu"');
const bdir = path.join(run.dataDir, 'backups'); const bk = fs.existsSync(bdir) ? fs.readdirSync(bdir) : [];
R.check('B2.automatic-backup-before-apply', bk.some((f) => /pre-import/.test(f)), bk, 'backup exampanel-backup-pre-import-*.db');
const txt = await bodyText(app.b); const shown = after.teachers.filter((t) => txt.includes(t.display_name || t.full_name)).length;
R.check('B2.data-visible-in-teacher-list', shown >= 11, { shown, of: 12, note: 'list may paginate' }, 'teachers visible');
await app.stop();
fs.writeFileSync(path.join(run.dir, 'out/GOLDEN.txt'), 'Q-shaped DB after real-UI import (B2). Source for later scenarios.');
console.log('GOLDEN RUN DIR', run.dir);
